function H = H_jacobian(x)
%H_jacobian
%    H = H_jacobian(X)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    03-Sep-2024 21:47:51

t2 = cos(x(7));
t3 = sin(x(7));
H = reshape([0.0,0.0,0.0,0.0,t2,0.0,0.0,0.0,0.0,0.0,t3,0.0,-t3.*x(3)+t2.*x(6),0.0,0.0,1.0],[2,8]);
end
