#include "customcode_neOgvabhESQorERU2TIrPE.h"
#ifdef __cplusplus
extern "C" {
#endif


/* Type Definitions */

/* Named Constants */

/* Variable Declarations */

/* Variable Definitions */

/* Function Declarations */
DLL_EXPORT_CC extern void get_fStateVector_addr_neOgvabhESQorERU2TIrPE(float32_t (**varAddr)[8]);
DLL_EXPORT_CC extern const char_T *get_dll_checksum_neOgvabhESQorERU2TIrPE(void);
DLL_EXPORT_CC extern void __cmsis_start_neOgvabhESQorERU2TIrPE(void);
DLL_EXPORT_CC extern void __ISB_neOgvabhESQorERU2TIrPE(void);
DLL_EXPORT_CC extern void __DSB_neOgvabhESQorERU2TIrPE(void);
DLL_EXPORT_CC extern void __DMB_neOgvabhESQorERU2TIrPE(void);
DLL_EXPORT_CC extern uint32_T __REV_neOgvabhESQorERU2TIrPE(uint32_T value);
DLL_EXPORT_CC extern uint32_T __REV16_neOgvabhESQorERU2TIrPE(uint32_T value);
DLL_EXPORT_CC extern int16_T __REVSH_neOgvabhESQorERU2TIrPE(int16_T value);
DLL_EXPORT_CC extern uint32_T __ROR_neOgvabhESQorERU2TIrPE(uint32_T op1, uint32_T op2);
DLL_EXPORT_CC extern uint32_T __RBIT_neOgvabhESQorERU2TIrPE(uint32_T value);
DLL_EXPORT_CC extern uint8_T __CLZ_neOgvabhESQorERU2TIrPE(uint32_T value);
DLL_EXPORT_CC extern int32_T __SSAT_neOgvabhESQorERU2TIrPE(int32_T val, uint32_T sat);
DLL_EXPORT_CC extern uint32_T __USAT_neOgvabhESQorERU2TIrPE(int32_T val, uint32_T sat);
DLL_EXPORT_CC extern void __enable_irq_neOgvabhESQorERU2TIrPE(void);
DLL_EXPORT_CC extern void __disable_irq_neOgvabhESQorERU2TIrPE(void);
DLL_EXPORT_CC extern uint32_T __get_CONTROL_neOgvabhESQorERU2TIrPE(void);
DLL_EXPORT_CC extern void __set_CONTROL_neOgvabhESQorERU2TIrPE(uint32_T control);
DLL_EXPORT_CC extern uint32_T __get_IPSR_neOgvabhESQorERU2TIrPE(void);
DLL_EXPORT_CC extern uint32_T __get_APSR_neOgvabhESQorERU2TIrPE(void);
DLL_EXPORT_CC extern uint32_T __get_xPSR_neOgvabhESQorERU2TIrPE(void);
DLL_EXPORT_CC extern uint32_T __get_PSP_neOgvabhESQorERU2TIrPE(void);
DLL_EXPORT_CC extern void __set_PSP_neOgvabhESQorERU2TIrPE(uint32_T topOfProcStack);
DLL_EXPORT_CC extern uint32_T __get_MSP_neOgvabhESQorERU2TIrPE(void);
DLL_EXPORT_CC extern void __set_MSP_neOgvabhESQorERU2TIrPE(uint32_T topOfMainStack);
DLL_EXPORT_CC extern uint32_T __get_PRIMASK_neOgvabhESQorERU2TIrPE(void);
DLL_EXPORT_CC extern void __set_PRIMASK_neOgvabhESQorERU2TIrPE(uint32_T priMask);
DLL_EXPORT_CC extern uint32_T __get_FPSCR_neOgvabhESQorERU2TIrPE(void);
DLL_EXPORT_CC extern void __set_FPSCR_neOgvabhESQorERU2TIrPE(uint32_T fpscr);
DLL_EXPORT_CC extern q31_t read_q15x2_neOgvabhESQorERU2TIrPE(const q15_t *pQ15);
DLL_EXPORT_CC extern void write_q15x2_ia_neOgvabhESQorERU2TIrPE(q15_t **pQ15, q31_t value);
DLL_EXPORT_CC extern void write_q15x2_neOgvabhESQorERU2TIrPE(q15_t *pQ15, q31_t value);
DLL_EXPORT_CC extern q31_t read_q7x4_neOgvabhESQorERU2TIrPE(const q7_t *pQ7);
DLL_EXPORT_CC extern void write_q7x4_ia_neOgvabhESQorERU2TIrPE(q7_t **pQ7, q31_t value);
DLL_EXPORT_CC extern q31_t clip_q63_to_q31_neOgvabhESQorERU2TIrPE(q63_t x);
DLL_EXPORT_CC extern q15_t clip_q63_to_q15_neOgvabhESQorERU2TIrPE(q63_t x);
DLL_EXPORT_CC extern q7_t clip_q31_to_q7_neOgvabhESQorERU2TIrPE(q31_t x);
DLL_EXPORT_CC extern q15_t clip_q31_to_q15_neOgvabhESQorERU2TIrPE(q31_t x);
DLL_EXPORT_CC extern q63_t mult32x64_neOgvabhESQorERU2TIrPE(q63_t x, q31_t y);
DLL_EXPORT_CC extern uint32_T __QADD8_neOgvabhESQorERU2TIrPE(uint32_T x, uint32_T y);
DLL_EXPORT_CC extern uint32_T __QSUB8_neOgvabhESQorERU2TIrPE(uint32_T x, uint32_T y);
DLL_EXPORT_CC extern uint32_T __QADD16_neOgvabhESQorERU2TIrPE(uint32_T x, uint32_T y);
DLL_EXPORT_CC extern uint32_T __SHADD16_neOgvabhESQorERU2TIrPE(uint32_T x, uint32_T y);
DLL_EXPORT_CC extern uint32_T __QSUB16_neOgvabhESQorERU2TIrPE(uint32_T x, uint32_T y);
DLL_EXPORT_CC extern uint32_T __SHSUB16_neOgvabhESQorERU2TIrPE(uint32_T x, uint32_T y);
DLL_EXPORT_CC extern uint32_T __QASX_neOgvabhESQorERU2TIrPE(uint32_T x, uint32_T y);
DLL_EXPORT_CC extern uint32_T __SHASX_neOgvabhESQorERU2TIrPE(uint32_T x, uint32_T y);
DLL_EXPORT_CC extern uint32_T __QSAX_neOgvabhESQorERU2TIrPE(uint32_T x, uint32_T y);
DLL_EXPORT_CC extern uint32_T __SHSAX_neOgvabhESQorERU2TIrPE(uint32_T x, uint32_T y);
DLL_EXPORT_CC extern uint32_T __SMUSDX_neOgvabhESQorERU2TIrPE(uint32_T x, uint32_T y);
DLL_EXPORT_CC extern uint32_T __SMUADX_neOgvabhESQorERU2TIrPE(uint32_T x, uint32_T y);
DLL_EXPORT_CC extern int32_T __QADD_neOgvabhESQorERU2TIrPE(int32_T x, int32_T y);
DLL_EXPORT_CC extern int32_T __QSUB_neOgvabhESQorERU2TIrPE(int32_T x, int32_T y);
DLL_EXPORT_CC extern uint32_T __SMLAD_neOgvabhESQorERU2TIrPE(uint32_T x, uint32_T y, uint32_T sum);
DLL_EXPORT_CC extern uint32_T __SMLADX_neOgvabhESQorERU2TIrPE(uint32_T x, uint32_T y, uint32_T sum);
DLL_EXPORT_CC extern uint32_T __SMLSDX_neOgvabhESQorERU2TIrPE(uint32_T x, uint32_T y, uint32_T sum);
DLL_EXPORT_CC extern uint64_T __SMLALD_neOgvabhESQorERU2TIrPE(uint32_T x, uint32_T y, uint64_T sum);
DLL_EXPORT_CC extern uint64_T __SMLALDX_neOgvabhESQorERU2TIrPE(uint32_T x, uint32_T y, uint64_T sum);
DLL_EXPORT_CC extern uint32_T __SMUAD_neOgvabhESQorERU2TIrPE(uint32_T x, uint32_T y);
DLL_EXPORT_CC extern uint32_T __SMUSD_neOgvabhESQorERU2TIrPE(uint32_T x, uint32_T y);
DLL_EXPORT_CC extern uint32_T __SXTB16_neOgvabhESQorERU2TIrPE(uint32_T x);
DLL_EXPORT_CC extern int32_T __SMMLA_neOgvabhESQorERU2TIrPE(int32_T x, int32_T y, int32_T sum);
DLL_EXPORT_CC extern uint32_T arm_recip_q31_neOgvabhESQorERU2TIrPE(q31_t in, q31_t *dst, const q31_t *pRecipTable);
DLL_EXPORT_CC extern uint32_T arm_recip_q15_neOgvabhESQorERU2TIrPE(q15_t in, q15_t *dst, const q15_t *pRecipTable);
DLL_EXPORT_CC extern void arm_norm_64_to_32u_neOgvabhESQorERU2TIrPE(uint64_T in, int32_T *normalized, int32_T *norm);
DLL_EXPORT_CC extern int32_T arm_div_int64_to_int32_neOgvabhESQorERU2TIrPE(int64_T num, int32_T den);
DLL_EXPORT_CC extern void arm_mult_q7_neOgvabhESQorERU2TIrPE(const q7_t *pSrcA, const q7_t *pSrcB, q7_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_mult_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrcA, const q15_t *pSrcB, q15_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_mult_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrcA, const q31_t *pSrcB, q31_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_mult_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrcA, const float32_t *pSrcB, float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_mult_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrcA, const float64_t *pSrcB, float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_add_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrcA, const float32_t *pSrcB, float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_add_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrcA, const float64_t *pSrcB, float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_add_q7_neOgvabhESQorERU2TIrPE(const q7_t *pSrcA, const q7_t *pSrcB, q7_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_add_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrcA, const q15_t *pSrcB, q15_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_add_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrcA, const q31_t *pSrcB, q31_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_sub_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrcA, const float32_t *pSrcB, float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_sub_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrcA, const float64_t *pSrcB, float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_sub_q7_neOgvabhESQorERU2TIrPE(const q7_t *pSrcA, const q7_t *pSrcB, q7_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_sub_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrcA, const q15_t *pSrcB, q15_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_sub_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrcA, const q31_t *pSrcB, q31_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_scale_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrc, float32_t scale, float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_scale_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrc, float64_t scale, float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_scale_q7_neOgvabhESQorERU2TIrPE(const q7_t *pSrc, q7_t scaleFract, int8_T shift, q7_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_scale_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrc, q15_t scaleFract, int8_T shift, q15_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_scale_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrc, q31_t scaleFract, int8_T shift, q31_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_abs_q7_neOgvabhESQorERU2TIrPE(const q7_t *pSrc, q7_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_abs_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrc, float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_abs_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrc, float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_abs_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrc, q15_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_abs_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrc, q31_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_dot_prod_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrcA, const float32_t *pSrcB, uint32_T blockSize, float32_t *result);
DLL_EXPORT_CC extern void arm_dot_prod_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrcA, const float64_t *pSrcB, uint32_T blockSize, float64_t *result);
DLL_EXPORT_CC extern void arm_dot_prod_q7_neOgvabhESQorERU2TIrPE(const q7_t *pSrcA, const q7_t *pSrcB, uint32_T blockSize, q31_t *result);
DLL_EXPORT_CC extern void arm_dot_prod_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrcA, const q15_t *pSrcB, uint32_T blockSize, q63_t *result);
DLL_EXPORT_CC extern void arm_dot_prod_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrcA, const q31_t *pSrcB, uint32_T blockSize, q63_t *result);
DLL_EXPORT_CC extern void arm_shift_q7_neOgvabhESQorERU2TIrPE(const q7_t *pSrc, int8_T shiftBits, q7_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_shift_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrc, int8_T shiftBits, q15_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_shift_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrc, int8_T shiftBits, q31_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_offset_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrc, float64_t offset, float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_offset_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrc, float32_t offset, float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_offset_q7_neOgvabhESQorERU2TIrPE(const q7_t *pSrc, q7_t offset, q7_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_offset_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrc, q15_t offset, q15_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_offset_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrc, q31_t offset, q31_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_negate_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrc, float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_negate_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrc, float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_negate_q7_neOgvabhESQorERU2TIrPE(const q7_t *pSrc, q7_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_negate_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrc, q15_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_negate_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrc, q31_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_and_u16_neOgvabhESQorERU2TIrPE(const uint16_T *pSrcA, const uint16_T *pSrcB, uint16_T *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_and_u32_neOgvabhESQorERU2TIrPE(const uint32_T *pSrcA, const uint32_T *pSrcB, uint32_T *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_and_u8_neOgvabhESQorERU2TIrPE(const uint8_T *pSrcA, const uint8_T *pSrcB, uint8_T *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_or_u16_neOgvabhESQorERU2TIrPE(const uint16_T *pSrcA, const uint16_T *pSrcB, uint16_T *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_or_u32_neOgvabhESQorERU2TIrPE(const uint32_T *pSrcA, const uint32_T *pSrcB, uint32_T *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_or_u8_neOgvabhESQorERU2TIrPE(const uint8_T *pSrcA, const uint8_T *pSrcB, uint8_T *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_not_u16_neOgvabhESQorERU2TIrPE(const uint16_T *pSrc, uint16_T *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_not_u32_neOgvabhESQorERU2TIrPE(const uint32_T *pSrc, uint32_T *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_not_u8_neOgvabhESQorERU2TIrPE(const uint8_T *pSrc, uint8_T *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_xor_u16_neOgvabhESQorERU2TIrPE(const uint16_T *pSrcA, const uint16_T *pSrcB, uint16_T *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_xor_u32_neOgvabhESQorERU2TIrPE(const uint32_T *pSrcA, const uint32_T *pSrcB, uint32_T *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_xor_u8_neOgvabhESQorERU2TIrPE(const uint8_T *pSrcA, const uint8_T *pSrcB, uint8_T *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_clip_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrc, float32_t *pDst, float32_t low, float32_t high, uint32_T numSamples);
DLL_EXPORT_CC extern void arm_clip_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrc, q31_t *pDst, q31_t low, q31_t high, uint32_T numSamples);
DLL_EXPORT_CC extern void arm_clip_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrc, q15_t *pDst, q15_t low, q15_t high, uint32_T numSamples);
DLL_EXPORT_CC extern void arm_clip_q7_neOgvabhESQorERU2TIrPE(const q7_t *pSrc, q7_t *pDst, q7_t low, q7_t high, uint32_T numSamples);
DLL_EXPORT_CC extern void arm_spline_f32_neOgvabhESQorERU2TIrPE(arm_spline_instance_f32 *S, const float32_t *xq, float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_spline_init_f32_neOgvabhESQorERU2TIrPE(arm_spline_instance_f32 *S, arm_spline_type type, const float32_t *x, const float32_t *y, uint32_T n, float32_t *coeffs, float32_t *tempBuffer);
DLL_EXPORT_CC extern float32_t arm_linear_interp_f32_neOgvabhESQorERU2TIrPE(const arm_linear_interp_instance_f32 *S, float32_t x);
DLL_EXPORT_CC extern q31_t arm_linear_interp_q31_neOgvabhESQorERU2TIrPE(const q31_t *pYData, q31_t x, uint32_T nValues);
DLL_EXPORT_CC extern q15_t arm_linear_interp_q15_neOgvabhESQorERU2TIrPE(const q15_t *pYData, q31_t x, uint32_T nValues);
DLL_EXPORT_CC extern q7_t arm_linear_interp_q7_neOgvabhESQorERU2TIrPE(const q7_t *pYData, q31_t x, uint32_T nValues);
DLL_EXPORT_CC extern float32_t arm_bilinear_interp_f32_neOgvabhESQorERU2TIrPE(const arm_bilinear_interp_instance_f32 *S, float32_t X, float32_t Y);
DLL_EXPORT_CC extern q31_t arm_bilinear_interp_q31_neOgvabhESQorERU2TIrPE(arm_bilinear_interp_instance_q31 *S, q31_t X, q31_t Y);
DLL_EXPORT_CC extern q15_t arm_bilinear_interp_q15_neOgvabhESQorERU2TIrPE(arm_bilinear_interp_instance_q15 *S, q31_t X, q31_t Y);
DLL_EXPORT_CC extern q7_t arm_bilinear_interp_q7_neOgvabhESQorERU2TIrPE(arm_bilinear_interp_instance_q7 *S, q31_t X, q31_t Y);
DLL_EXPORT_CC extern float32_t arm_sin_f32_neOgvabhESQorERU2TIrPE(float32_t x);
DLL_EXPORT_CC extern q31_t arm_sin_q31_neOgvabhESQorERU2TIrPE(q31_t x);
DLL_EXPORT_CC extern q15_t arm_sin_q15_neOgvabhESQorERU2TIrPE(q15_t x);
DLL_EXPORT_CC extern float32_t arm_cos_f32_neOgvabhESQorERU2TIrPE(float32_t x);
DLL_EXPORT_CC extern q31_t arm_cos_q31_neOgvabhESQorERU2TIrPE(q31_t x);
DLL_EXPORT_CC extern q15_t arm_cos_q15_neOgvabhESQorERU2TIrPE(q15_t x);
DLL_EXPORT_CC extern void arm_vlog_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrc, float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_vlog_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrc, float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_vlog_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrc, q31_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_vlog_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrc, q15_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_vexp_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrc, float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_vexp_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrc, float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern arm_status arm_sqrt_f32_neOgvabhESQorERU2TIrPE(const float32_t in, float32_t *pOut);
DLL_EXPORT_CC extern arm_status arm_sqrt_q31_neOgvabhESQorERU2TIrPE(q31_t in, q31_t *pOut);
DLL_EXPORT_CC extern arm_status arm_sqrt_q15_neOgvabhESQorERU2TIrPE(q15_t in, q15_t *pOut);
DLL_EXPORT_CC extern arm_status arm_divide_q15_neOgvabhESQorERU2TIrPE(q15_t numerator, q15_t denominator, q15_t *quotient, int16_T *shift);
DLL_EXPORT_CC extern arm_status arm_divide_q31_neOgvabhESQorERU2TIrPE(q31_t numerator, q31_t denominator, q31_t *quotient, int16_T *shift);
DLL_EXPORT_CC extern arm_status arm_atan2_f32_neOgvabhESQorERU2TIrPE(float32_t y, float32_t x, float32_t *result);
DLL_EXPORT_CC extern arm_status arm_atan2_q31_neOgvabhESQorERU2TIrPE(q31_t y, q31_t x, q31_t *result);
DLL_EXPORT_CC extern arm_status arm_atan2_q15_neOgvabhESQorERU2TIrPE(q15_t y, q15_t x, q15_t *result);
DLL_EXPORT_CC extern float32_t arm_logsumexp_f32_neOgvabhESQorERU2TIrPE(const float32_t *in, uint32_T blockSize);
DLL_EXPORT_CC extern float32_t arm_logsumexp_dot_prod_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrcA, const float32_t *pSrcB, uint32_T blockSize, float32_t *pTmpBuffer);
DLL_EXPORT_CC extern float32_t arm_entropy_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrcA, uint32_T blockSize);
DLL_EXPORT_CC extern float64_t arm_entropy_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrcA, uint32_T blockSize);
DLL_EXPORT_CC extern float32_t arm_kullback_leibler_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrcA, const float32_t *pSrcB, uint32_T blockSize);
DLL_EXPORT_CC extern float64_t arm_kullback_leibler_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrcA, const float64_t *pSrcB, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_power_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrc, uint32_T blockSize, q63_t *pResult);
DLL_EXPORT_CC extern void arm_power_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrc, uint32_T blockSize, float32_t *pResult);
DLL_EXPORT_CC extern void arm_power_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrc, uint32_T blockSize, float64_t *pResult);
DLL_EXPORT_CC extern void arm_power_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrc, uint32_T blockSize, q63_t *pResult);
DLL_EXPORT_CC extern void arm_power_q7_neOgvabhESQorERU2TIrPE(const q7_t *pSrc, uint32_T blockSize, q31_t *pResult);
DLL_EXPORT_CC extern void arm_mean_q7_neOgvabhESQorERU2TIrPE(const q7_t *pSrc, uint32_T blockSize, q7_t *pResult);
DLL_EXPORT_CC extern void arm_mean_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrc, uint32_T blockSize, q15_t *pResult);
DLL_EXPORT_CC extern void arm_mean_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrc, uint32_T blockSize, q31_t *pResult);
DLL_EXPORT_CC extern void arm_mean_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrc, uint32_T blockSize, float32_t *pResult);
DLL_EXPORT_CC extern void arm_mean_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrc, uint32_T blockSize, float64_t *pResult);
DLL_EXPORT_CC extern void arm_var_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrc, uint32_T blockSize, float32_t *pResult);
DLL_EXPORT_CC extern void arm_var_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrc, uint32_T blockSize, float64_t *pResult);
DLL_EXPORT_CC extern void arm_var_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrc, uint32_T blockSize, q31_t *pResult);
DLL_EXPORT_CC extern void arm_var_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrc, uint32_T blockSize, q15_t *pResult);
DLL_EXPORT_CC extern void arm_rms_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrc, uint32_T blockSize, float32_t *pResult);
DLL_EXPORT_CC extern void arm_rms_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrc, uint32_T blockSize, q31_t *pResult);
DLL_EXPORT_CC extern void arm_rms_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrc, uint32_T blockSize, q15_t *pResult);
DLL_EXPORT_CC extern void arm_std_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrc, uint32_T blockSize, float32_t *pResult);
DLL_EXPORT_CC extern void arm_std_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrc, uint32_T blockSize, float64_t *pResult);
DLL_EXPORT_CC extern void arm_std_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrc, uint32_T blockSize, q31_t *pResult);
DLL_EXPORT_CC extern void arm_std_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrc, uint32_T blockSize, q15_t *pResult);
DLL_EXPORT_CC extern void arm_min_q7_neOgvabhESQorERU2TIrPE(const q7_t *pSrc, uint32_T blockSize, q7_t *pResult, uint32_T *pIndex);
DLL_EXPORT_CC extern void arm_absmin_q7_neOgvabhESQorERU2TIrPE(const q7_t *pSrc, uint32_T blockSize, q7_t *pResult, uint32_T *pIndex);
DLL_EXPORT_CC extern void arm_absmin_no_idx_q7_neOgvabhESQorERU2TIrPE(const q7_t *pSrc, uint32_T blockSize, q7_t *pResult);
DLL_EXPORT_CC extern void arm_min_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrc, uint32_T blockSize, q15_t *pResult, uint32_T *pIndex);
DLL_EXPORT_CC extern void arm_absmin_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrc, uint32_T blockSize, q15_t *pResult, uint32_T *pIndex);
DLL_EXPORT_CC extern void arm_absmin_no_idx_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrc, uint32_T blockSize, q15_t *pResult);
DLL_EXPORT_CC extern void arm_min_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrc, uint32_T blockSize, q31_t *pResult, uint32_T *pIndex);
DLL_EXPORT_CC extern void arm_absmin_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrc, uint32_T blockSize, q31_t *pResult, uint32_T *pIndex);
DLL_EXPORT_CC extern void arm_absmin_no_idx_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrc, uint32_T blockSize, q31_t *pResult);
DLL_EXPORT_CC extern void arm_min_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrc, uint32_T blockSize, float32_t *pResult, uint32_T *pIndex);
DLL_EXPORT_CC extern void arm_absmin_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrc, uint32_T blockSize, float32_t *pResult, uint32_T *pIndex);
DLL_EXPORT_CC extern void arm_absmin_no_idx_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrc, uint32_T blockSize, float32_t *pResult);
DLL_EXPORT_CC extern void arm_min_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrc, uint32_T blockSize, float64_t *pResult, uint32_T *pIndex);
DLL_EXPORT_CC extern void arm_absmin_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrc, uint32_T blockSize, float64_t *pResult, uint32_T *pIndex);
DLL_EXPORT_CC extern void arm_absmin_no_idx_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrc, uint32_T blockSize, float64_t *pResult);
DLL_EXPORT_CC extern void arm_max_q7_neOgvabhESQorERU2TIrPE(const q7_t *pSrc, uint32_T blockSize, q7_t *pResult, uint32_T *pIndex);
DLL_EXPORT_CC extern void arm_absmax_q7_neOgvabhESQorERU2TIrPE(const q7_t *pSrc, uint32_T blockSize, q7_t *pResult, uint32_T *pIndex);
DLL_EXPORT_CC extern void arm_absmax_no_idx_q7_neOgvabhESQorERU2TIrPE(const q7_t *pSrc, uint32_T blockSize, q7_t *pResult);
DLL_EXPORT_CC extern void arm_max_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrc, uint32_T blockSize, q15_t *pResult, uint32_T *pIndex);
DLL_EXPORT_CC extern void arm_absmax_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrc, uint32_T blockSize, q15_t *pResult, uint32_T *pIndex);
DLL_EXPORT_CC extern void arm_absmax_no_idx_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrc, uint32_T blockSize, q15_t *pResult);
DLL_EXPORT_CC extern void arm_max_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrc, uint32_T blockSize, q31_t *pResult, uint32_T *pIndex);
DLL_EXPORT_CC extern void arm_absmax_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrc, uint32_T blockSize, q31_t *pResult, uint32_T *pIndex);
DLL_EXPORT_CC extern void arm_absmax_no_idx_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrc, uint32_T blockSize, q31_t *pResult);
DLL_EXPORT_CC extern void arm_max_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrc, uint32_T blockSize, float32_t *pResult, uint32_T *pIndex);
DLL_EXPORT_CC extern void arm_absmax_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrc, uint32_T blockSize, float32_t *pResult, uint32_T *pIndex);
DLL_EXPORT_CC extern void arm_absmax_no_idx_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrc, uint32_T blockSize, float32_t *pResult);
DLL_EXPORT_CC extern void arm_max_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrc, uint32_T blockSize, float64_t *pResult, uint32_T *pIndex);
DLL_EXPORT_CC extern void arm_absmax_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrc, uint32_T blockSize, float64_t *pResult, uint32_T *pIndex);
DLL_EXPORT_CC extern void arm_absmax_no_idx_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrc, uint32_T blockSize, float64_t *pResult);
DLL_EXPORT_CC extern void arm_max_no_idx_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrc, uint32_T blockSize, float32_t *pResult);
DLL_EXPORT_CC extern void arm_min_no_idx_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrc, uint32_T blockSize, float32_t *pResult);
DLL_EXPORT_CC extern void arm_max_no_idx_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrc, uint32_T blockSize, float64_t *pResult);
DLL_EXPORT_CC extern void arm_max_no_idx_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrc, uint32_T blockSize, q31_t *pResult);
DLL_EXPORT_CC extern void arm_max_no_idx_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrc, uint32_T blockSize, q15_t *pResult);
DLL_EXPORT_CC extern void arm_max_no_idx_q7_neOgvabhESQorERU2TIrPE(const q7_t *pSrc, uint32_T blockSize, q7_t *pResult);
DLL_EXPORT_CC extern void arm_min_no_idx_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrc, uint32_T blockSize, float64_t *pResult);
DLL_EXPORT_CC extern void arm_min_no_idx_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrc, uint32_T blockSize, q31_t *pResult);
DLL_EXPORT_CC extern void arm_min_no_idx_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrc, uint32_T blockSize, q15_t *pResult);
DLL_EXPORT_CC extern void arm_min_no_idx_q7_neOgvabhESQorERU2TIrPE(const q7_t *pSrc, uint32_T blockSize, q7_t *pResult);
DLL_EXPORT_CC extern void arm_mse_q7_neOgvabhESQorERU2TIrPE(const q7_t *pSrcA, const q7_t *pSrcB, uint32_T blockSize, q7_t *pResult);
DLL_EXPORT_CC extern void arm_mse_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrcA, const q15_t *pSrcB, uint32_T blockSize, q15_t *pResult);
DLL_EXPORT_CC extern void arm_mse_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrcA, const q31_t *pSrcB, uint32_T blockSize, q31_t *pResult);
DLL_EXPORT_CC extern void arm_mse_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrcA, const float32_t *pSrcB, uint32_T blockSize, float32_t *pResult);
DLL_EXPORT_CC extern void arm_mse_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrcA, const float64_t *pSrcB, uint32_T blockSize, float64_t *pResult);
DLL_EXPORT_CC extern void arm_accumulate_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrc, uint32_T blockSize, float32_t *pResult);
DLL_EXPORT_CC extern void arm_accumulate_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrc, uint32_T blockSize, float64_t *pResult);
DLL_EXPORT_CC extern uint32_T arm_gaussian_naive_bayes_predict_f32_neOgvabhESQorERU2TIrPE(const arm_gaussian_naive_bayes_instance_f32 *S, const float32_t *in, float32_t *pOutputProbabilities, float32_t *pBufferB);
DLL_EXPORT_CC extern arm_status arm_mat_add_f32_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_f32 *pSrcA, const arm_matrix_instance_f32 *pSrcB, arm_matrix_instance_f32 *pDst);
DLL_EXPORT_CC extern arm_status arm_mat_add_q15_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_q15 *pSrcA, const arm_matrix_instance_q15 *pSrcB, arm_matrix_instance_q15 *pDst);
DLL_EXPORT_CC extern arm_status arm_mat_add_q31_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_q31 *pSrcA, const arm_matrix_instance_q31 *pSrcB, arm_matrix_instance_q31 *pDst);
DLL_EXPORT_CC extern arm_status arm_mat_cmplx_mult_f32_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_f32 *pSrcA, const arm_matrix_instance_f32 *pSrcB, arm_matrix_instance_f32 *pDst);
DLL_EXPORT_CC extern arm_status arm_mat_cmplx_mult_q15_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_q15 *pSrcA, const arm_matrix_instance_q15 *pSrcB, arm_matrix_instance_q15 *pDst, q15_t *pScratch);
DLL_EXPORT_CC extern arm_status arm_mat_cmplx_mult_q31_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_q31 *pSrcA, const arm_matrix_instance_q31 *pSrcB, arm_matrix_instance_q31 *pDst);
DLL_EXPORT_CC extern arm_status arm_mat_trans_f32_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_f32 *pSrc, arm_matrix_instance_f32 *pDst);
DLL_EXPORT_CC extern arm_status arm_mat_trans_f64_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_f64 *pSrc, arm_matrix_instance_f64 *pDst);
DLL_EXPORT_CC extern arm_status arm_mat_cmplx_trans_f32_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_f32 *pSrc, arm_matrix_instance_f32 *pDst);
DLL_EXPORT_CC extern arm_status arm_mat_trans_q15_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_q15 *pSrc, arm_matrix_instance_q15 *pDst);
DLL_EXPORT_CC extern arm_status arm_mat_cmplx_trans_q15_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_q15 *pSrc, arm_matrix_instance_q15 *pDst);
DLL_EXPORT_CC extern arm_status arm_mat_trans_q7_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_q7 *pSrc, arm_matrix_instance_q7 *pDst);
DLL_EXPORT_CC extern arm_status arm_mat_trans_q31_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_q31 *pSrc, arm_matrix_instance_q31 *pDst);
DLL_EXPORT_CC extern arm_status arm_mat_cmplx_trans_q31_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_q31 *pSrc, arm_matrix_instance_q31 *pDst);
DLL_EXPORT_CC extern arm_status arm_mat_mult_f32_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_f32 *pSrcA, const arm_matrix_instance_f32 *pSrcB, arm_matrix_instance_f32 *pDst);
DLL_EXPORT_CC extern arm_status arm_mat_mult_f64_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_f64 *pSrcA, const arm_matrix_instance_f64 *pSrcB, arm_matrix_instance_f64 *pDst);
DLL_EXPORT_CC extern void arm_mat_vec_mult_f32_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_f32 *pSrcMat, const float32_t *pVec, float32_t *pDst);
DLL_EXPORT_CC extern arm_status arm_mat_mult_q7_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_q7 *pSrcA, const arm_matrix_instance_q7 *pSrcB, arm_matrix_instance_q7 *pDst, q7_t *pState);
DLL_EXPORT_CC extern void arm_mat_vec_mult_q7_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_q7 *pSrcMat, const q7_t *pVec, q7_t *pDst);
DLL_EXPORT_CC extern arm_status arm_mat_mult_q15_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_q15 *pSrcA, const arm_matrix_instance_q15 *pSrcB, arm_matrix_instance_q15 *pDst, q15_t *pState);
DLL_EXPORT_CC extern void arm_mat_vec_mult_q15_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_q15 *pSrcMat, const q15_t *pVec, q15_t *pDst);
DLL_EXPORT_CC extern arm_status arm_mat_mult_fast_q15_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_q15 *pSrcA, const arm_matrix_instance_q15 *pSrcB, arm_matrix_instance_q15 *pDst, q15_t *pState);
DLL_EXPORT_CC extern arm_status arm_mat_mult_q31_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_q31 *pSrcA, const arm_matrix_instance_q31 *pSrcB, arm_matrix_instance_q31 *pDst);
DLL_EXPORT_CC extern arm_status arm_mat_mult_opt_q31_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_q31 *pSrcA, const arm_matrix_instance_q31 *pSrcB, arm_matrix_instance_q31 *pDst, q31_t *pState);
DLL_EXPORT_CC extern void arm_mat_vec_mult_q31_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_q31 *pSrcMat, const q31_t *pVec, q31_t *pDst);
DLL_EXPORT_CC extern arm_status arm_mat_mult_fast_q31_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_q31 *pSrcA, const arm_matrix_instance_q31 *pSrcB, arm_matrix_instance_q31 *pDst);
DLL_EXPORT_CC extern arm_status arm_mat_sub_f32_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_f32 *pSrcA, const arm_matrix_instance_f32 *pSrcB, arm_matrix_instance_f32 *pDst);
DLL_EXPORT_CC extern arm_status arm_mat_sub_f64_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_f64 *pSrcA, const arm_matrix_instance_f64 *pSrcB, arm_matrix_instance_f64 *pDst);
DLL_EXPORT_CC extern arm_status arm_mat_sub_q15_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_q15 *pSrcA, const arm_matrix_instance_q15 *pSrcB, arm_matrix_instance_q15 *pDst);
DLL_EXPORT_CC extern arm_status arm_mat_sub_q31_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_q31 *pSrcA, const arm_matrix_instance_q31 *pSrcB, arm_matrix_instance_q31 *pDst);
DLL_EXPORT_CC extern arm_status arm_mat_scale_f32_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_f32 *pSrc, float32_t scale, arm_matrix_instance_f32 *pDst);
DLL_EXPORT_CC extern arm_status arm_mat_scale_q15_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_q15 *pSrc, q15_t scaleFract, int32_T shift, arm_matrix_instance_q15 *pDst);
DLL_EXPORT_CC extern arm_status arm_mat_scale_q31_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_q31 *pSrc, q31_t scaleFract, int32_T shift, arm_matrix_instance_q31 *pDst);
DLL_EXPORT_CC extern void arm_mat_init_q31_neOgvabhESQorERU2TIrPE(arm_matrix_instance_q31 *S, uint16_T nRows, uint16_T nColumns, q31_t *pData);
DLL_EXPORT_CC extern void arm_mat_init_q15_neOgvabhESQorERU2TIrPE(arm_matrix_instance_q15 *S, uint16_T nRows, uint16_T nColumns, q15_t *pData);
DLL_EXPORT_CC extern void arm_mat_init_f32_neOgvabhESQorERU2TIrPE(arm_matrix_instance_f32 *S, uint16_T nRows, uint16_T nColumns, float32_t *pData);
DLL_EXPORT_CC extern void arm_mat_init_f64_neOgvabhESQorERU2TIrPE(arm_matrix_instance_f64 *S, uint16_T nRows, uint16_T nColumns, float64_t *pData);
DLL_EXPORT_CC extern arm_status arm_mat_inverse_f32_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_f32 *src, arm_matrix_instance_f32 *dst);
DLL_EXPORT_CC extern arm_status arm_mat_inverse_f64_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_f64 *src, arm_matrix_instance_f64 *dst);
DLL_EXPORT_CC extern arm_status arm_mat_cholesky_f64_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_f64 *src, arm_matrix_instance_f64 *dst);
DLL_EXPORT_CC extern arm_status arm_mat_cholesky_f32_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_f32 *src, arm_matrix_instance_f32 *dst);
DLL_EXPORT_CC extern arm_status arm_mat_solve_upper_triangular_f32_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_f32 *ut, const arm_matrix_instance_f32 *a, arm_matrix_instance_f32 *dst);
DLL_EXPORT_CC extern arm_status arm_mat_solve_lower_triangular_f32_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_f32 *lt, const arm_matrix_instance_f32 *a, arm_matrix_instance_f32 *dst);
DLL_EXPORT_CC extern arm_status arm_mat_solve_upper_triangular_f64_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_f64 *ut, const arm_matrix_instance_f64 *a, arm_matrix_instance_f64 *dst);
DLL_EXPORT_CC extern arm_status arm_mat_solve_lower_triangular_f64_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_f64 *lt, const arm_matrix_instance_f64 *a, arm_matrix_instance_f64 *dst);
DLL_EXPORT_CC extern arm_status arm_mat_ldlt_f32_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_f32 *src, arm_matrix_instance_f32 *l, arm_matrix_instance_f32 *d, uint16_T *pp);
DLL_EXPORT_CC extern arm_status arm_mat_ldlt_f64_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_f64 *src, arm_matrix_instance_f64 *l, arm_matrix_instance_f64 *d, uint16_T *pp);
DLL_EXPORT_CC extern arm_status arm_mat_qr_f32_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_f32 *pSrc, const float32_t threshold, arm_matrix_instance_f32 *pOutR, arm_matrix_instance_f32 *pOutQ, float32_t *pOutTau, float32_t *pTmpA, float32_t *pTmpB);
DLL_EXPORT_CC extern arm_status arm_mat_qr_f64_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_f64 *pSrc, const float64_t threshold, arm_matrix_instance_f64 *pOutR, arm_matrix_instance_f64 *pOutQ, float64_t *pOutTau, float64_t *pTmpA, float64_t *pTmpB);
DLL_EXPORT_CC extern float32_t arm_householder_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrc, const float32_t threshold, uint32_T blockSize, float32_t *pOut);
DLL_EXPORT_CC extern float64_t arm_householder_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrc, const float64_t threshold, uint32_T blockSize, float64_t *pOut);
DLL_EXPORT_CC extern void arm_cmplx_conj_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrc, float32_t *pDst, uint32_T numSamples);
DLL_EXPORT_CC extern void arm_cmplx_conj_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrc, q31_t *pDst, uint32_T numSamples);
DLL_EXPORT_CC extern void arm_cmplx_conj_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrc, q15_t *pDst, uint32_T numSamples);
DLL_EXPORT_CC extern void arm_cmplx_mag_squared_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrc, float32_t *pDst, uint32_T numSamples);
DLL_EXPORT_CC extern void arm_cmplx_mag_squared_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrc, float64_t *pDst, uint32_T numSamples);
DLL_EXPORT_CC extern void arm_cmplx_mag_squared_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrc, q31_t *pDst, uint32_T numSamples);
DLL_EXPORT_CC extern void arm_cmplx_mag_squared_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrc, q15_t *pDst, uint32_T numSamples);
DLL_EXPORT_CC extern void arm_cmplx_mag_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrc, float32_t *pDst, uint32_T numSamples);
DLL_EXPORT_CC extern void arm_cmplx_mag_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrc, float64_t *pDst, uint32_T numSamples);
DLL_EXPORT_CC extern void arm_cmplx_mag_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrc, q31_t *pDst, uint32_T numSamples);
DLL_EXPORT_CC extern void arm_cmplx_mag_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrc, q15_t *pDst, uint32_T numSamples);
DLL_EXPORT_CC extern void arm_cmplx_mag_fast_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrc, q15_t *pDst, uint32_T numSamples);
DLL_EXPORT_CC extern void arm_cmplx_dot_prod_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrcA, const q15_t *pSrcB, uint32_T numSamples, q31_t *realResult, q31_t *imagResult);
DLL_EXPORT_CC extern void arm_cmplx_dot_prod_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrcA, const q31_t *pSrcB, uint32_T numSamples, q63_t *realResult, q63_t *imagResult);
DLL_EXPORT_CC extern void arm_cmplx_dot_prod_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrcA, const float32_t *pSrcB, uint32_T numSamples, float32_t *realResult, float32_t *imagResult);
DLL_EXPORT_CC extern void arm_cmplx_mult_real_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrcCmplx, const q15_t *pSrcReal, q15_t *pCmplxDst, uint32_T numSamples);
DLL_EXPORT_CC extern void arm_cmplx_mult_real_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrcCmplx, const q31_t *pSrcReal, q31_t *pCmplxDst, uint32_T numSamples);
DLL_EXPORT_CC extern void arm_cmplx_mult_real_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrcCmplx, const float32_t *pSrcReal, float32_t *pCmplxDst, uint32_T numSamples);
DLL_EXPORT_CC extern void arm_cmplx_mult_cmplx_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrcA, const q15_t *pSrcB, q15_t *pDst, uint32_T numSamples);
DLL_EXPORT_CC extern void arm_cmplx_mult_cmplx_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrcA, const q31_t *pSrcB, q31_t *pDst, uint32_T numSamples);
DLL_EXPORT_CC extern void arm_cmplx_mult_cmplx_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrcA, const float32_t *pSrcB, float32_t *pDst, uint32_T numSamples);
DLL_EXPORT_CC extern void arm_cmplx_mult_cmplx_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrcA, const float64_t *pSrcB, float64_t *pDst, uint32_T numSamples);
DLL_EXPORT_CC extern void arm_sin_cos_f32_neOgvabhESQorERU2TIrPE(float32_t theta, float32_t *pSinVal, float32_t *pCosVal);
DLL_EXPORT_CC extern void arm_sin_cos_q31_neOgvabhESQorERU2TIrPE(q31_t theta, q31_t *pSinVal, q31_t *pCosVal);
DLL_EXPORT_CC extern void arm_pid_init_f32_neOgvabhESQorERU2TIrPE(arm_pid_instance_f32 *S, int32_T resetStateFlag);
DLL_EXPORT_CC extern void arm_pid_reset_f32_neOgvabhESQorERU2TIrPE(arm_pid_instance_f32 *S);
DLL_EXPORT_CC extern void arm_pid_init_q31_neOgvabhESQorERU2TIrPE(arm_pid_instance_q31 *S, int32_T resetStateFlag);
DLL_EXPORT_CC extern void arm_pid_reset_q31_neOgvabhESQorERU2TIrPE(arm_pid_instance_q31 *S);
DLL_EXPORT_CC extern void arm_pid_init_q15_neOgvabhESQorERU2TIrPE(arm_pid_instance_q15 *S, int32_T resetStateFlag);
DLL_EXPORT_CC extern void arm_pid_reset_q15_neOgvabhESQorERU2TIrPE(arm_pid_instance_q15 *S);
DLL_EXPORT_CC extern float32_t arm_pid_f32_neOgvabhESQorERU2TIrPE(arm_pid_instance_f32 *S, float32_t in);
DLL_EXPORT_CC extern q31_t arm_pid_q31_neOgvabhESQorERU2TIrPE(arm_pid_instance_q31 *S, q31_t in);
DLL_EXPORT_CC extern q15_t arm_pid_q15_neOgvabhESQorERU2TIrPE(arm_pid_instance_q15 *S, q15_t in);
DLL_EXPORT_CC extern void arm_park_f32_neOgvabhESQorERU2TIrPE(float32_t Ialpha, float32_t Ibeta, float32_t *pId, float32_t *pIq, float32_t sinVal, float32_t cosVal);
DLL_EXPORT_CC extern void arm_park_q31_neOgvabhESQorERU2TIrPE(q31_t Ialpha, q31_t Ibeta, q31_t *pId, q31_t *pIq, q31_t sinVal, q31_t cosVal);
DLL_EXPORT_CC extern void arm_inv_park_f32_neOgvabhESQorERU2TIrPE(float32_t Id, float32_t Iq, float32_t *pIalpha, float32_t *pIbeta, float32_t sinVal, float32_t cosVal);
DLL_EXPORT_CC extern void arm_inv_park_q31_neOgvabhESQorERU2TIrPE(q31_t Id, q31_t Iq, q31_t *pIalpha, q31_t *pIbeta, q31_t sinVal, q31_t cosVal);
DLL_EXPORT_CC extern void arm_clarke_f32_neOgvabhESQorERU2TIrPE(float32_t Ia, float32_t Ib, float32_t *pIalpha, float32_t *pIbeta);
DLL_EXPORT_CC extern void arm_clarke_q31_neOgvabhESQorERU2TIrPE(q31_t Ia, q31_t Ib, q31_t *pIalpha, q31_t *pIbeta);
DLL_EXPORT_CC extern void arm_inv_clarke_f32_neOgvabhESQorERU2TIrPE(float32_t Ialpha, float32_t Ibeta, float32_t *pIa, float32_t *pIb);
DLL_EXPORT_CC extern void arm_inv_clarke_q31_neOgvabhESQorERU2TIrPE(q31_t Ialpha, q31_t Ibeta, q31_t *pIa, q31_t *pIb);
DLL_EXPORT_CC extern void arm_f64_to_float_neOgvabhESQorERU2TIrPE(const float64_t *pSrc, float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_f64_to_q31_neOgvabhESQorERU2TIrPE(const float64_t *pSrc, q31_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_f64_to_q15_neOgvabhESQorERU2TIrPE(const float64_t *pSrc, q15_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_f64_to_q7_neOgvabhESQorERU2TIrPE(const float64_t *pSrc, q7_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_float_to_f64_neOgvabhESQorERU2TIrPE(const float32_t *pSrc, float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_float_to_q31_neOgvabhESQorERU2TIrPE(const float32_t *pSrc, q31_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_float_to_q15_neOgvabhESQorERU2TIrPE(const float32_t *pSrc, q15_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_float_to_q7_neOgvabhESQorERU2TIrPE(const float32_t *pSrc, q7_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_q31_to_f64_neOgvabhESQorERU2TIrPE(const q31_t *pSrc, float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_q31_to_float_neOgvabhESQorERU2TIrPE(const q31_t *pSrc, float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_q31_to_q15_neOgvabhESQorERU2TIrPE(const q31_t *pSrc, q15_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_q31_to_q7_neOgvabhESQorERU2TIrPE(const q31_t *pSrc, q7_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_q15_to_f64_neOgvabhESQorERU2TIrPE(const q15_t *pSrc, float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_q15_to_float_neOgvabhESQorERU2TIrPE(const q15_t *pSrc, float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_q15_to_q31_neOgvabhESQorERU2TIrPE(const q15_t *pSrc, q31_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_q15_to_q7_neOgvabhESQorERU2TIrPE(const q15_t *pSrc, q7_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_q7_to_f64_neOgvabhESQorERU2TIrPE(const q7_t *pSrc, float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_q7_to_float_neOgvabhESQorERU2TIrPE(const q7_t *pSrc, float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_q7_to_q31_neOgvabhESQorERU2TIrPE(const q7_t *pSrc, q31_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_q7_to_q15_neOgvabhESQorERU2TIrPE(const q7_t *pSrc, q15_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_sort_f32_neOgvabhESQorERU2TIrPE(const arm_sort_instance_f32 *S, float32_t *pSrc, float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_sort_init_f32_neOgvabhESQorERU2TIrPE(arm_sort_instance_f32 *S, arm_sort_alg alg, arm_sort_dir dir);
DLL_EXPORT_CC extern void arm_merge_sort_f32_neOgvabhESQorERU2TIrPE(const arm_merge_sort_instance_f32 *S, float32_t *pSrc, float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_merge_sort_init_f32_neOgvabhESQorERU2TIrPE(arm_merge_sort_instance_f32 *S, arm_sort_dir dir, float32_t *buffer);
DLL_EXPORT_CC extern void arm_copy_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrc, float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_copy_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrc, float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_copy_q7_neOgvabhESQorERU2TIrPE(const q7_t *pSrc, q7_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_copy_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrc, q15_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_copy_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrc, q31_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fill_f32_neOgvabhESQorERU2TIrPE(float32_t value, float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fill_f64_neOgvabhESQorERU2TIrPE(float64_t value, float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fill_q7_neOgvabhESQorERU2TIrPE(q7_t value, q7_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fill_q15_neOgvabhESQorERU2TIrPE(q15_t value, q15_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fill_q31_neOgvabhESQorERU2TIrPE(q31_t value, q31_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern float32_t arm_weighted_average_f32_neOgvabhESQorERU2TIrPE(const float32_t *in, const float32_t *weigths, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_barycenter_f32_neOgvabhESQorERU2TIrPE(const float32_t *in, const float32_t *weights, float32_t *out, uint32_T nbVectors, uint32_T vecDim);
DLL_EXPORT_CC extern float32_t arm_euclidean_distance_f32_neOgvabhESQorERU2TIrPE(const float32_t *pA, const float32_t *pB, uint32_T blockSize);
DLL_EXPORT_CC extern float64_t arm_euclidean_distance_f64_neOgvabhESQorERU2TIrPE(const float64_t *pA, const float64_t *pB, uint32_T blockSize);
DLL_EXPORT_CC extern float32_t arm_braycurtis_distance_f32_neOgvabhESQorERU2TIrPE(const float32_t *pA, const float32_t *pB, uint32_T blockSize);
DLL_EXPORT_CC extern float32_t arm_canberra_distance_f32_neOgvabhESQorERU2TIrPE(const float32_t *pA, const float32_t *pB, uint32_T blockSize);
DLL_EXPORT_CC extern float32_t arm_chebyshev_distance_f32_neOgvabhESQorERU2TIrPE(const float32_t *pA, const float32_t *pB, uint32_T blockSize);
DLL_EXPORT_CC extern float64_t arm_chebyshev_distance_f64_neOgvabhESQorERU2TIrPE(const float64_t *pA, const float64_t *pB, uint32_T blockSize);
DLL_EXPORT_CC extern float32_t arm_cityblock_distance_f32_neOgvabhESQorERU2TIrPE(const float32_t *pA, const float32_t *pB, uint32_T blockSize);
DLL_EXPORT_CC extern float64_t arm_cityblock_distance_f64_neOgvabhESQorERU2TIrPE(const float64_t *pA, const float64_t *pB, uint32_T blockSize);
DLL_EXPORT_CC extern float32_t arm_correlation_distance_f32_neOgvabhESQorERU2TIrPE(float32_t *pA, float32_t *pB, uint32_T blockSize);
DLL_EXPORT_CC extern float32_t arm_cosine_distance_f32_neOgvabhESQorERU2TIrPE(const float32_t *pA, const float32_t *pB, uint32_T blockSize);
DLL_EXPORT_CC extern float64_t arm_cosine_distance_f64_neOgvabhESQorERU2TIrPE(const float64_t *pA, const float64_t *pB, uint32_T blockSize);
DLL_EXPORT_CC extern float32_t arm_jensenshannon_distance_f32_neOgvabhESQorERU2TIrPE(const float32_t *pA, const float32_t *pB, uint32_T blockSize);
DLL_EXPORT_CC extern float32_t arm_minkowski_distance_f32_neOgvabhESQorERU2TIrPE(const float32_t *pA, const float32_t *pB, int32_T order, uint32_T blockSize);
DLL_EXPORT_CC extern float32_t arm_dice_distance_neOgvabhESQorERU2TIrPE(const uint32_T *pA, const uint32_T *pB, uint32_T numberOfBools);
DLL_EXPORT_CC extern float32_t arm_hamming_distance_neOgvabhESQorERU2TIrPE(const uint32_T *pA, const uint32_T *pB, uint32_T numberOfBools);
DLL_EXPORT_CC extern float32_t arm_jaccard_distance_neOgvabhESQorERU2TIrPE(const uint32_T *pA, const uint32_T *pB, uint32_T numberOfBools);
DLL_EXPORT_CC extern float32_t arm_kulsinski_distance_neOgvabhESQorERU2TIrPE(const uint32_T *pA, const uint32_T *pB, uint32_T numberOfBools);
DLL_EXPORT_CC extern float32_t arm_rogerstanimoto_distance_neOgvabhESQorERU2TIrPE(const uint32_T *pA, const uint32_T *pB, uint32_T numberOfBools);
DLL_EXPORT_CC extern float32_t arm_russellrao_distance_neOgvabhESQorERU2TIrPE(const uint32_T *pA, const uint32_T *pB, uint32_T numberOfBools);
DLL_EXPORT_CC extern float32_t arm_sokalmichener_distance_neOgvabhESQorERU2TIrPE(const uint32_T *pA, const uint32_T *pB, uint32_T numberOfBools);
DLL_EXPORT_CC extern float32_t arm_sokalsneath_distance_neOgvabhESQorERU2TIrPE(const uint32_T *pA, const uint32_T *pB, uint32_T numberOfBools);
DLL_EXPORT_CC extern float32_t arm_yule_distance_neOgvabhESQorERU2TIrPE(const uint32_T *pA, const uint32_T *pB, uint32_T numberOfBools);
DLL_EXPORT_CC extern arm_status arm_dtw_init_window_q7_neOgvabhESQorERU2TIrPE(const arm_dtw_window windowType, const int32_T windowSize, arm_matrix_instance_q7 *pWindow);
DLL_EXPORT_CC extern arm_status arm_dtw_distance_f32_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_f32 *pDistance, const arm_matrix_instance_q7 *pWindow, arm_matrix_instance_f32 *pDTW, float32_t *distance);
DLL_EXPORT_CC extern void arm_dtw_path_f32_neOgvabhESQorERU2TIrPE(const arm_matrix_instance_f32 *pDTW, int16_T *pPath, uint32_T *pathLength);
DLL_EXPORT_CC extern float32_t arm_exponent_f32_neOgvabhESQorERU2TIrPE(float32_t x, int32_T nb);
DLL_EXPORT_CC extern void arm_svm_linear_init_f32_neOgvabhESQorERU2TIrPE(arm_svm_linear_instance_f32 *S, uint32_T nbOfSupportVectors, uint32_T vectorDimension, float32_t intercept, const float32_t *dualCoefficients, const float32_t *supportVectors, const int32_T *classes);
DLL_EXPORT_CC extern void arm_svm_linear_predict_f32_neOgvabhESQorERU2TIrPE(const arm_svm_linear_instance_f32 *S, const float32_t *in, int32_T *pResult);
DLL_EXPORT_CC extern void arm_svm_polynomial_init_f32_neOgvabhESQorERU2TIrPE(arm_svm_polynomial_instance_f32 *S, uint32_T nbOfSupportVectors, uint32_T vectorDimension, float32_t intercept, const float32_t *dualCoefficients, const float32_t *supportVectors, const int32_T *classes, int32_T degree, float32_t coef0, float32_t gamma);
DLL_EXPORT_CC extern void arm_svm_polynomial_predict_f32_neOgvabhESQorERU2TIrPE(const arm_svm_polynomial_instance_f32 *S, const float32_t *in, int32_T *pResult);
DLL_EXPORT_CC extern void arm_svm_rbf_init_f32_neOgvabhESQorERU2TIrPE(arm_svm_rbf_instance_f32 *S, uint32_T nbOfSupportVectors, uint32_T vectorDimension, float32_t intercept, const float32_t *dualCoefficients, const float32_t *supportVectors, const int32_T *classes, float32_t gamma);
DLL_EXPORT_CC extern void arm_svm_rbf_predict_f32_neOgvabhESQorERU2TIrPE(const arm_svm_rbf_instance_f32 *S, const float32_t *in, int32_T *pResult);
DLL_EXPORT_CC extern void arm_svm_sigmoid_init_f32_neOgvabhESQorERU2TIrPE(arm_svm_sigmoid_instance_f32 *S, uint32_T nbOfSupportVectors, uint32_T vectorDimension, float32_t intercept, const float32_t *dualCoefficients, const float32_t *supportVectors, const int32_T *classes, float32_t coef0, float32_t gamma);
DLL_EXPORT_CC extern void arm_svm_sigmoid_predict_f32_neOgvabhESQorERU2TIrPE(const arm_svm_sigmoid_instance_f32 *S, const float32_t *in, int32_T *pResult);
DLL_EXPORT_CC extern void arm_cfft_radix2_q15_neOgvabhESQorERU2TIrPE(const arm_cfft_radix2_instance_q15 *S, q15_t *pSrc);
DLL_EXPORT_CC extern arm_status arm_cfft_radix4_init_q15_neOgvabhESQorERU2TIrPE(arm_cfft_radix4_instance_q15 *S, uint16_T fftLen, uint8_T ifftFlag, uint8_T bitReverseFlag);
DLL_EXPORT_CC extern void arm_cfft_radix4_q15_neOgvabhESQorERU2TIrPE(const arm_cfft_radix4_instance_q15 *S, q15_t *pSrc);
DLL_EXPORT_CC extern void arm_cfft_radix2_q31_neOgvabhESQorERU2TIrPE(const arm_cfft_radix2_instance_q31 *S, q31_t *pSrc);
DLL_EXPORT_CC extern void arm_cfft_radix4_q31_neOgvabhESQorERU2TIrPE(const arm_cfft_radix4_instance_q31 *S, q31_t *pSrc);
DLL_EXPORT_CC extern arm_status arm_cfft_radix4_init_q31_neOgvabhESQorERU2TIrPE(arm_cfft_radix4_instance_q31 *S, uint16_T fftLen, uint8_T ifftFlag, uint8_T bitReverseFlag);
DLL_EXPORT_CC extern void arm_cfft_radix2_f32_neOgvabhESQorERU2TIrPE(const arm_cfft_radix2_instance_f32 *S, float32_t *pSrc);
DLL_EXPORT_CC extern arm_status arm_cfft_radix4_init_f32_neOgvabhESQorERU2TIrPE(arm_cfft_radix4_instance_f32 *S, uint16_T fftLen, uint8_T ifftFlag, uint8_T bitReverseFlag);
DLL_EXPORT_CC extern void arm_cfft_radix4_f32_neOgvabhESQorERU2TIrPE(const arm_cfft_radix4_instance_f32 *S, float32_t *pSrc);
DLL_EXPORT_CC extern arm_status arm_cfft_init_4096_q15_neOgvabhESQorERU2TIrPE(arm_cfft_instance_q15 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_2048_q15_neOgvabhESQorERU2TIrPE(arm_cfft_instance_q15 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_1024_q15_neOgvabhESQorERU2TIrPE(arm_cfft_instance_q15 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_512_q15_neOgvabhESQorERU2TIrPE(arm_cfft_instance_q15 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_256_q15_neOgvabhESQorERU2TIrPE(arm_cfft_instance_q15 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_128_q15_neOgvabhESQorERU2TIrPE(arm_cfft_instance_q15 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_64_q15_neOgvabhESQorERU2TIrPE(arm_cfft_instance_q15 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_32_q15_neOgvabhESQorERU2TIrPE(arm_cfft_instance_q15 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_16_q15_neOgvabhESQorERU2TIrPE(arm_cfft_instance_q15 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_q15_neOgvabhESQorERU2TIrPE(arm_cfft_instance_q15 *S, uint16_T fftLen);
DLL_EXPORT_CC extern void arm_cfft_q15_neOgvabhESQorERU2TIrPE(const arm_cfft_instance_q15 *S, q15_t *p1, uint8_T ifftFlag, uint8_T bitReverseFlag);
DLL_EXPORT_CC extern arm_status arm_cfft_init_4096_q31_neOgvabhESQorERU2TIrPE(arm_cfft_instance_q31 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_2048_q31_neOgvabhESQorERU2TIrPE(arm_cfft_instance_q31 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_1024_q31_neOgvabhESQorERU2TIrPE(arm_cfft_instance_q31 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_512_q31_neOgvabhESQorERU2TIrPE(arm_cfft_instance_q31 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_256_q31_neOgvabhESQorERU2TIrPE(arm_cfft_instance_q31 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_128_q31_neOgvabhESQorERU2TIrPE(arm_cfft_instance_q31 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_64_q31_neOgvabhESQorERU2TIrPE(arm_cfft_instance_q31 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_32_q31_neOgvabhESQorERU2TIrPE(arm_cfft_instance_q31 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_16_q31_neOgvabhESQorERU2TIrPE(arm_cfft_instance_q31 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_q31_neOgvabhESQorERU2TIrPE(arm_cfft_instance_q31 *S, uint16_T fftLen);
DLL_EXPORT_CC extern void arm_cfft_q31_neOgvabhESQorERU2TIrPE(const arm_cfft_instance_q31 *S, q31_t *p1, uint8_T ifftFlag, uint8_T bitReverseFlag);
DLL_EXPORT_CC extern arm_status arm_cfft_init_4096_f32_neOgvabhESQorERU2TIrPE(arm_cfft_instance_f32 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_2048_f32_neOgvabhESQorERU2TIrPE(arm_cfft_instance_f32 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_1024_f32_neOgvabhESQorERU2TIrPE(arm_cfft_instance_f32 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_512_f32_neOgvabhESQorERU2TIrPE(arm_cfft_instance_f32 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_256_f32_neOgvabhESQorERU2TIrPE(arm_cfft_instance_f32 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_128_f32_neOgvabhESQorERU2TIrPE(arm_cfft_instance_f32 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_64_f32_neOgvabhESQorERU2TIrPE(arm_cfft_instance_f32 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_32_f32_neOgvabhESQorERU2TIrPE(arm_cfft_instance_f32 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_16_f32_neOgvabhESQorERU2TIrPE(arm_cfft_instance_f32 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_f32_neOgvabhESQorERU2TIrPE(arm_cfft_instance_f32 *S, uint16_T fftLen);
DLL_EXPORT_CC extern void arm_cfft_f32_neOgvabhESQorERU2TIrPE(const arm_cfft_instance_f32 *S, float32_t *p1, uint8_T ifftFlag, uint8_T bitReverseFlag);
DLL_EXPORT_CC extern arm_status arm_cfft_init_4096_f64_neOgvabhESQorERU2TIrPE(arm_cfft_instance_f64 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_2048_f64_neOgvabhESQorERU2TIrPE(arm_cfft_instance_f64 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_1024_f64_neOgvabhESQorERU2TIrPE(arm_cfft_instance_f64 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_512_f64_neOgvabhESQorERU2TIrPE(arm_cfft_instance_f64 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_256_f64_neOgvabhESQorERU2TIrPE(arm_cfft_instance_f64 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_128_f64_neOgvabhESQorERU2TIrPE(arm_cfft_instance_f64 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_64_f64_neOgvabhESQorERU2TIrPE(arm_cfft_instance_f64 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_32_f64_neOgvabhESQorERU2TIrPE(arm_cfft_instance_f64 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_16_f64_neOgvabhESQorERU2TIrPE(arm_cfft_instance_f64 *S);
DLL_EXPORT_CC extern arm_status arm_cfft_init_f64_neOgvabhESQorERU2TIrPE(arm_cfft_instance_f64 *S, uint16_T fftLen);
DLL_EXPORT_CC extern void arm_cfft_f64_neOgvabhESQorERU2TIrPE(const arm_cfft_instance_f64 *S, float64_t *p1, uint8_T ifftFlag, uint8_T bitReverseFlag);
DLL_EXPORT_CC extern arm_status arm_rfft_init_32_q15_neOgvabhESQorERU2TIrPE(arm_rfft_instance_q15 *S, uint32_T ifftFlagR, uint32_T bitReverseFlag);
DLL_EXPORT_CC extern arm_status arm_rfft_init_64_q15_neOgvabhESQorERU2TIrPE(arm_rfft_instance_q15 *S, uint32_T ifftFlagR, uint32_T bitReverseFlag);
DLL_EXPORT_CC extern arm_status arm_rfft_init_128_q15_neOgvabhESQorERU2TIrPE(arm_rfft_instance_q15 *S, uint32_T ifftFlagR, uint32_T bitReverseFlag);
DLL_EXPORT_CC extern arm_status arm_rfft_init_256_q15_neOgvabhESQorERU2TIrPE(arm_rfft_instance_q15 *S, uint32_T ifftFlagR, uint32_T bitReverseFlag);
DLL_EXPORT_CC extern arm_status arm_rfft_init_512_q15_neOgvabhESQorERU2TIrPE(arm_rfft_instance_q15 *S, uint32_T ifftFlagR, uint32_T bitReverseFlag);
DLL_EXPORT_CC extern arm_status arm_rfft_init_1024_q15_neOgvabhESQorERU2TIrPE(arm_rfft_instance_q15 *S, uint32_T ifftFlagR, uint32_T bitReverseFlag);
DLL_EXPORT_CC extern arm_status arm_rfft_init_2048_q15_neOgvabhESQorERU2TIrPE(arm_rfft_instance_q15 *S, uint32_T ifftFlagR, uint32_T bitReverseFlag);
DLL_EXPORT_CC extern arm_status arm_rfft_init_4096_q15_neOgvabhESQorERU2TIrPE(arm_rfft_instance_q15 *S, uint32_T ifftFlagR, uint32_T bitReverseFlag);
DLL_EXPORT_CC extern arm_status arm_rfft_init_8192_q15_neOgvabhESQorERU2TIrPE(arm_rfft_instance_q15 *S, uint32_T ifftFlagR, uint32_T bitReverseFlag);
DLL_EXPORT_CC extern arm_status arm_rfft_init_q15_neOgvabhESQorERU2TIrPE(arm_rfft_instance_q15 *S, uint32_T fftLenReal, uint32_T ifftFlagR, uint32_T bitReverseFlag);
DLL_EXPORT_CC extern void arm_rfft_q15_neOgvabhESQorERU2TIrPE(const arm_rfft_instance_q15 *S, q15_t *pSrc, q15_t *pDst);
DLL_EXPORT_CC extern arm_status arm_rfft_init_32_q31_neOgvabhESQorERU2TIrPE(arm_rfft_instance_q31 *S, uint32_T ifftFlagR, uint32_T bitReverseFlag);
DLL_EXPORT_CC extern arm_status arm_rfft_init_64_q31_neOgvabhESQorERU2TIrPE(arm_rfft_instance_q31 *S, uint32_T ifftFlagR, uint32_T bitReverseFlag);
DLL_EXPORT_CC extern arm_status arm_rfft_init_128_q31_neOgvabhESQorERU2TIrPE(arm_rfft_instance_q31 *S, uint32_T ifftFlagR, uint32_T bitReverseFlag);
DLL_EXPORT_CC extern arm_status arm_rfft_init_256_q31_neOgvabhESQorERU2TIrPE(arm_rfft_instance_q31 *S, uint32_T ifftFlagR, uint32_T bitReverseFlag);
DLL_EXPORT_CC extern arm_status arm_rfft_init_512_q31_neOgvabhESQorERU2TIrPE(arm_rfft_instance_q31 *S, uint32_T ifftFlagR, uint32_T bitReverseFlag);
DLL_EXPORT_CC extern arm_status arm_rfft_init_1024_q31_neOgvabhESQorERU2TIrPE(arm_rfft_instance_q31 *S, uint32_T ifftFlagR, uint32_T bitReverseFlag);
DLL_EXPORT_CC extern arm_status arm_rfft_init_2048_q31_neOgvabhESQorERU2TIrPE(arm_rfft_instance_q31 *S, uint32_T ifftFlagR, uint32_T bitReverseFlag);
DLL_EXPORT_CC extern arm_status arm_rfft_init_4096_q31_neOgvabhESQorERU2TIrPE(arm_rfft_instance_q31 *S, uint32_T ifftFlagR, uint32_T bitReverseFlag);
DLL_EXPORT_CC extern arm_status arm_rfft_init_8192_q31_neOgvabhESQorERU2TIrPE(arm_rfft_instance_q31 *S, uint32_T ifftFlagR, uint32_T bitReverseFlag);
DLL_EXPORT_CC extern arm_status arm_rfft_init_q31_neOgvabhESQorERU2TIrPE(arm_rfft_instance_q31 *S, uint32_T fftLenReal, uint32_T ifftFlagR, uint32_T bitReverseFlag);
DLL_EXPORT_CC extern void arm_rfft_q31_neOgvabhESQorERU2TIrPE(const arm_rfft_instance_q31 *S, q31_t *pSrc, q31_t *pDst);
DLL_EXPORT_CC extern arm_status arm_rfft_init_f32_neOgvabhESQorERU2TIrPE(arm_rfft_instance_f32 *S, arm_cfft_radix4_instance_f32 *S_CFFT, uint32_T fftLenReal, uint32_T ifftFlagR, uint32_T bitReverseFlag);
DLL_EXPORT_CC extern void arm_rfft_f32_neOgvabhESQorERU2TIrPE(const arm_rfft_instance_f32 *S, float32_t *pSrc, float32_t *pDst);
DLL_EXPORT_CC extern arm_status arm_rfft_fast_init_32_f64_neOgvabhESQorERU2TIrPE(arm_rfft_fast_instance_f64 *S);
DLL_EXPORT_CC extern arm_status arm_rfft_fast_init_64_f64_neOgvabhESQorERU2TIrPE(arm_rfft_fast_instance_f64 *S);
DLL_EXPORT_CC extern arm_status arm_rfft_fast_init_128_f64_neOgvabhESQorERU2TIrPE(arm_rfft_fast_instance_f64 *S);
DLL_EXPORT_CC extern arm_status arm_rfft_fast_init_256_f64_neOgvabhESQorERU2TIrPE(arm_rfft_fast_instance_f64 *S);
DLL_EXPORT_CC extern arm_status arm_rfft_fast_init_512_f64_neOgvabhESQorERU2TIrPE(arm_rfft_fast_instance_f64 *S);
DLL_EXPORT_CC extern arm_status arm_rfft_fast_init_1024_f64_neOgvabhESQorERU2TIrPE(arm_rfft_fast_instance_f64 *S);
DLL_EXPORT_CC extern arm_status arm_rfft_fast_init_2048_f64_neOgvabhESQorERU2TIrPE(arm_rfft_fast_instance_f64 *S);
DLL_EXPORT_CC extern arm_status arm_rfft_fast_init_4096_f64_neOgvabhESQorERU2TIrPE(arm_rfft_fast_instance_f64 *S);
DLL_EXPORT_CC extern arm_status arm_rfft_fast_init_f64_neOgvabhESQorERU2TIrPE(arm_rfft_fast_instance_f64 *S, uint16_T fftLen);
DLL_EXPORT_CC extern void arm_rfft_fast_f64_neOgvabhESQorERU2TIrPE(arm_rfft_fast_instance_f64 *S, float64_t *p, float64_t *pOut, uint8_T ifftFlag);
DLL_EXPORT_CC extern arm_status arm_rfft_fast_init_32_f32_neOgvabhESQorERU2TIrPE(arm_rfft_fast_instance_f32 *S);
DLL_EXPORT_CC extern arm_status arm_rfft_fast_init_64_f32_neOgvabhESQorERU2TIrPE(arm_rfft_fast_instance_f32 *S);
DLL_EXPORT_CC extern arm_status arm_rfft_fast_init_128_f32_neOgvabhESQorERU2TIrPE(arm_rfft_fast_instance_f32 *S);
DLL_EXPORT_CC extern arm_status arm_rfft_fast_init_256_f32_neOgvabhESQorERU2TIrPE(arm_rfft_fast_instance_f32 *S);
DLL_EXPORT_CC extern arm_status arm_rfft_fast_init_512_f32_neOgvabhESQorERU2TIrPE(arm_rfft_fast_instance_f32 *S);
DLL_EXPORT_CC extern arm_status arm_rfft_fast_init_1024_f32_neOgvabhESQorERU2TIrPE(arm_rfft_fast_instance_f32 *S);
DLL_EXPORT_CC extern arm_status arm_rfft_fast_init_2048_f32_neOgvabhESQorERU2TIrPE(arm_rfft_fast_instance_f32 *S);
DLL_EXPORT_CC extern arm_status arm_rfft_fast_init_4096_f32_neOgvabhESQorERU2TIrPE(arm_rfft_fast_instance_f32 *S);
DLL_EXPORT_CC extern arm_status arm_rfft_fast_init_f32_neOgvabhESQorERU2TIrPE(arm_rfft_fast_instance_f32 *S, uint16_T fftLen);
DLL_EXPORT_CC extern void arm_rfft_fast_f32_neOgvabhESQorERU2TIrPE(const arm_rfft_fast_instance_f32 *S, float32_t *p, float32_t *pOut, uint8_T ifftFlag);
DLL_EXPORT_CC extern arm_status arm_dct4_init_f32_neOgvabhESQorERU2TIrPE(arm_dct4_instance_f32 *S, arm_rfft_instance_f32 *S_RFFT, arm_cfft_radix4_instance_f32 *S_CFFT, uint16_T N, uint16_T Nby2, float32_t normalize);
DLL_EXPORT_CC extern void arm_dct4_f32_neOgvabhESQorERU2TIrPE(const arm_dct4_instance_f32 *S, float32_t *pState, float32_t *pInlineBuffer);
DLL_EXPORT_CC extern arm_status arm_dct4_init_q31_neOgvabhESQorERU2TIrPE(arm_dct4_instance_q31 *S, arm_rfft_instance_q31 *S_RFFT, arm_cfft_radix4_instance_q31 *S_CFFT, uint16_T N, uint16_T Nby2, q31_t normalize);
DLL_EXPORT_CC extern void arm_dct4_q31_neOgvabhESQorERU2TIrPE(const arm_dct4_instance_q31 *S, q31_t *pState, q31_t *pInlineBuffer);
DLL_EXPORT_CC extern arm_status arm_dct4_init_q15_neOgvabhESQorERU2TIrPE(arm_dct4_instance_q15 *S, arm_rfft_instance_q15 *S_RFFT, arm_cfft_radix4_instance_q15 *S_CFFT, uint16_T N, uint16_T Nby2, q15_t normalize);
DLL_EXPORT_CC extern void arm_dct4_q15_neOgvabhESQorERU2TIrPE(const arm_dct4_instance_q15 *S, q15_t *pState, q15_t *pInlineBuffer);
DLL_EXPORT_CC extern arm_status arm_mfcc_init_32_f32_neOgvabhESQorERU2TIrPE(arm_mfcc_instance_f32 *S, uint32_T nbMelFilters, uint32_T nbDctOutputs, const float32_t *dctCoefs, const uint32_T *filterPos, const uint32_T *filterLengths, const float32_t *filterCoefs, const float32_t *windowCoefs);
DLL_EXPORT_CC extern arm_status arm_mfcc_init_64_f32_neOgvabhESQorERU2TIrPE(arm_mfcc_instance_f32 *S, uint32_T nbMelFilters, uint32_T nbDctOutputs, const float32_t *dctCoefs, const uint32_T *filterPos, const uint32_T *filterLengths, const float32_t *filterCoefs, const float32_t *windowCoefs);
DLL_EXPORT_CC extern arm_status arm_mfcc_init_128_f32_neOgvabhESQorERU2TIrPE(arm_mfcc_instance_f32 *S, uint32_T nbMelFilters, uint32_T nbDctOutputs, const float32_t *dctCoefs, const uint32_T *filterPos, const uint32_T *filterLengths, const float32_t *filterCoefs, const float32_t *windowCoefs);
DLL_EXPORT_CC extern arm_status arm_mfcc_init_256_f32_neOgvabhESQorERU2TIrPE(arm_mfcc_instance_f32 *S, uint32_T nbMelFilters, uint32_T nbDctOutputs, const float32_t *dctCoefs, const uint32_T *filterPos, const uint32_T *filterLengths, const float32_t *filterCoefs, const float32_t *windowCoefs);
DLL_EXPORT_CC extern arm_status arm_mfcc_init_512_f32_neOgvabhESQorERU2TIrPE(arm_mfcc_instance_f32 *S, uint32_T nbMelFilters, uint32_T nbDctOutputs, const float32_t *dctCoefs, const uint32_T *filterPos, const uint32_T *filterLengths, const float32_t *filterCoefs, const float32_t *windowCoefs);
DLL_EXPORT_CC extern arm_status arm_mfcc_init_1024_f32_neOgvabhESQorERU2TIrPE(arm_mfcc_instance_f32 *S, uint32_T nbMelFilters, uint32_T nbDctOutputs, const float32_t *dctCoefs, const uint32_T *filterPos, const uint32_T *filterLengths, const float32_t *filterCoefs, const float32_t *windowCoefs);
DLL_EXPORT_CC extern arm_status arm_mfcc_init_2048_f32_neOgvabhESQorERU2TIrPE(arm_mfcc_instance_f32 *S, uint32_T nbMelFilters, uint32_T nbDctOutputs, const float32_t *dctCoefs, const uint32_T *filterPos, const uint32_T *filterLengths, const float32_t *filterCoefs, const float32_t *windowCoefs);
DLL_EXPORT_CC extern arm_status arm_mfcc_init_4096_f32_neOgvabhESQorERU2TIrPE(arm_mfcc_instance_f32 *S, uint32_T nbMelFilters, uint32_T nbDctOutputs, const float32_t *dctCoefs, const uint32_T *filterPos, const uint32_T *filterLengths, const float32_t *filterCoefs, const float32_t *windowCoefs);
DLL_EXPORT_CC extern arm_status arm_mfcc_init_f32_neOgvabhESQorERU2TIrPE(arm_mfcc_instance_f32 *S, uint32_T fftLen, uint32_T nbMelFilters, uint32_T nbDctOutputs, const float32_t *dctCoefs, const uint32_T *filterPos, const uint32_T *filterLengths, const float32_t *filterCoefs, const float32_t *windowCoefs);
DLL_EXPORT_CC extern void arm_mfcc_f32_neOgvabhESQorERU2TIrPE(const arm_mfcc_instance_f32 *S, float32_t *pSrc, float32_t *pDst, float32_t *pTmp);
DLL_EXPORT_CC extern arm_status arm_mfcc_init_32_q31_neOgvabhESQorERU2TIrPE(arm_mfcc_instance_q31 *S, uint32_T nbMelFilters, uint32_T nbDctOutputs, const q31_t *dctCoefs, const uint32_T *filterPos, const uint32_T *filterLengths, const q31_t *filterCoefs, const q31_t *windowCoefs);
DLL_EXPORT_CC extern arm_status arm_mfcc_init_64_q31_neOgvabhESQorERU2TIrPE(arm_mfcc_instance_q31 *S, uint32_T nbMelFilters, uint32_T nbDctOutputs, const q31_t *dctCoefs, const uint32_T *filterPos, const uint32_T *filterLengths, const q31_t *filterCoefs, const q31_t *windowCoefs);
DLL_EXPORT_CC extern arm_status arm_mfcc_init_128_q31_neOgvabhESQorERU2TIrPE(arm_mfcc_instance_q31 *S, uint32_T nbMelFilters, uint32_T nbDctOutputs, const q31_t *dctCoefs, const uint32_T *filterPos, const uint32_T *filterLengths, const q31_t *filterCoefs, const q31_t *windowCoefs);
DLL_EXPORT_CC extern arm_status arm_mfcc_init_256_q31_neOgvabhESQorERU2TIrPE(arm_mfcc_instance_q31 *S, uint32_T nbMelFilters, uint32_T nbDctOutputs, const q31_t *dctCoefs, const uint32_T *filterPos, const uint32_T *filterLengths, const q31_t *filterCoefs, const q31_t *windowCoefs);
DLL_EXPORT_CC extern arm_status arm_mfcc_init_512_q31_neOgvabhESQorERU2TIrPE(arm_mfcc_instance_q31 *S, uint32_T nbMelFilters, uint32_T nbDctOutputs, const q31_t *dctCoefs, const uint32_T *filterPos, const uint32_T *filterLengths, const q31_t *filterCoefs, const q31_t *windowCoefs);
DLL_EXPORT_CC extern arm_status arm_mfcc_init_1024_q31_neOgvabhESQorERU2TIrPE(arm_mfcc_instance_q31 *S, uint32_T nbMelFilters, uint32_T nbDctOutputs, const q31_t *dctCoefs, const uint32_T *filterPos, const uint32_T *filterLengths, const q31_t *filterCoefs, const q31_t *windowCoefs);
DLL_EXPORT_CC extern arm_status arm_mfcc_init_2048_q31_neOgvabhESQorERU2TIrPE(arm_mfcc_instance_q31 *S, uint32_T nbMelFilters, uint32_T nbDctOutputs, const q31_t *dctCoefs, const uint32_T *filterPos, const uint32_T *filterLengths, const q31_t *filterCoefs, const q31_t *windowCoefs);
DLL_EXPORT_CC extern arm_status arm_mfcc_init_4096_q31_neOgvabhESQorERU2TIrPE(arm_mfcc_instance_q31 *S, uint32_T nbMelFilters, uint32_T nbDctOutputs, const q31_t *dctCoefs, const uint32_T *filterPos, const uint32_T *filterLengths, const q31_t *filterCoefs, const q31_t *windowCoefs);
DLL_EXPORT_CC extern arm_status arm_mfcc_init_q31_neOgvabhESQorERU2TIrPE(arm_mfcc_instance_q31 *S, uint32_T fftLen, uint32_T nbMelFilters, uint32_T nbDctOutputs, const q31_t *dctCoefs, const uint32_T *filterPos, const uint32_T *filterLengths, const q31_t *filterCoefs, const q31_t *windowCoefs);
DLL_EXPORT_CC extern arm_status arm_mfcc_q31_neOgvabhESQorERU2TIrPE(const arm_mfcc_instance_q31 *S, q31_t *pSrc, q31_t *pDst, q31_t *pTmp);
DLL_EXPORT_CC extern arm_status arm_mfcc_init_32_q15_neOgvabhESQorERU2TIrPE(arm_mfcc_instance_q15 *S, uint32_T nbMelFilters, uint32_T nbDctOutputs, const q15_t *dctCoefs, const uint32_T *filterPos, const uint32_T *filterLengths, const q15_t *filterCoefs, const q15_t *windowCoefs);
DLL_EXPORT_CC extern arm_status arm_mfcc_init_64_q15_neOgvabhESQorERU2TIrPE(arm_mfcc_instance_q15 *S, uint32_T nbMelFilters, uint32_T nbDctOutputs, const q15_t *dctCoefs, const uint32_T *filterPos, const uint32_T *filterLengths, const q15_t *filterCoefs, const q15_t *windowCoefs);
DLL_EXPORT_CC extern arm_status arm_mfcc_init_128_q15_neOgvabhESQorERU2TIrPE(arm_mfcc_instance_q15 *S, uint32_T nbMelFilters, uint32_T nbDctOutputs, const q15_t *dctCoefs, const uint32_T *filterPos, const uint32_T *filterLengths, const q15_t *filterCoefs, const q15_t *windowCoefs);
DLL_EXPORT_CC extern arm_status arm_mfcc_init_256_q15_neOgvabhESQorERU2TIrPE(arm_mfcc_instance_q15 *S, uint32_T nbMelFilters, uint32_T nbDctOutputs, const q15_t *dctCoefs, const uint32_T *filterPos, const uint32_T *filterLengths, const q15_t *filterCoefs, const q15_t *windowCoefs);
DLL_EXPORT_CC extern arm_status arm_mfcc_init_512_q15_neOgvabhESQorERU2TIrPE(arm_mfcc_instance_q15 *S, uint32_T nbMelFilters, uint32_T nbDctOutputs, const q15_t *dctCoefs, const uint32_T *filterPos, const uint32_T *filterLengths, const q15_t *filterCoefs, const q15_t *windowCoefs);
DLL_EXPORT_CC extern arm_status arm_mfcc_init_1024_q15_neOgvabhESQorERU2TIrPE(arm_mfcc_instance_q15 *S, uint32_T nbMelFilters, uint32_T nbDctOutputs, const q15_t *dctCoefs, const uint32_T *filterPos, const uint32_T *filterLengths, const q15_t *filterCoefs, const q15_t *windowCoefs);
DLL_EXPORT_CC extern arm_status arm_mfcc_init_2048_q15_neOgvabhESQorERU2TIrPE(arm_mfcc_instance_q15 *S, uint32_T nbMelFilters, uint32_T nbDctOutputs, const q15_t *dctCoefs, const uint32_T *filterPos, const uint32_T *filterLengths, const q15_t *filterCoefs, const q15_t *windowCoefs);
DLL_EXPORT_CC extern arm_status arm_mfcc_init_4096_q15_neOgvabhESQorERU2TIrPE(arm_mfcc_instance_q15 *S, uint32_T nbMelFilters, uint32_T nbDctOutputs, const q15_t *dctCoefs, const uint32_T *filterPos, const uint32_T *filterLengths, const q15_t *filterCoefs, const q15_t *windowCoefs);
DLL_EXPORT_CC extern arm_status arm_mfcc_init_q15_neOgvabhESQorERU2TIrPE(arm_mfcc_instance_q15 *S, uint32_T fftLen, uint32_T nbMelFilters, uint32_T nbDctOutputs, const q15_t *dctCoefs, const uint32_T *filterPos, const uint32_T *filterLengths, const q15_t *filterCoefs, const q15_t *windowCoefs);
DLL_EXPORT_CC extern arm_status arm_mfcc_q15_neOgvabhESQorERU2TIrPE(const arm_mfcc_instance_q15 *S, q15_t *pSrc, q15_t *pDst, q31_t *pTmp);
DLL_EXPORT_CC extern void arm_fir_q7_neOgvabhESQorERU2TIrPE(const arm_fir_instance_q7 *S, const q7_t *pSrc, q7_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fir_init_q7_neOgvabhESQorERU2TIrPE(arm_fir_instance_q7 *S, uint16_T numTaps, const q7_t *pCoeffs, q7_t *pState, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fir_q15_neOgvabhESQorERU2TIrPE(const arm_fir_instance_q15 *S, const q15_t *pSrc, q15_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fir_fast_q15_neOgvabhESQorERU2TIrPE(const arm_fir_instance_q15 *S, const q15_t *pSrc, q15_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern arm_status arm_fir_init_q15_neOgvabhESQorERU2TIrPE(arm_fir_instance_q15 *S, uint16_T numTaps, const q15_t *pCoeffs, q15_t *pState, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fir_q31_neOgvabhESQorERU2TIrPE(const arm_fir_instance_q31 *S, const q31_t *pSrc, q31_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fir_fast_q31_neOgvabhESQorERU2TIrPE(const arm_fir_instance_q31 *S, const q31_t *pSrc, q31_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fir_init_q31_neOgvabhESQorERU2TIrPE(arm_fir_instance_q31 *S, uint16_T numTaps, const q31_t *pCoeffs, q31_t *pState, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fir_f32_neOgvabhESQorERU2TIrPE(const arm_fir_instance_f32 *S, const float32_t *pSrc, float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fir_f64_neOgvabhESQorERU2TIrPE(const arm_fir_instance_f64 *S, const float64_t *pSrc, float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fir_init_f32_neOgvabhESQorERU2TIrPE(arm_fir_instance_f32 *S, uint16_T numTaps, const float32_t *pCoeffs, float32_t *pState, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fir_init_f64_neOgvabhESQorERU2TIrPE(arm_fir_instance_f64 *S, uint16_T numTaps, const float64_t *pCoeffs, float64_t *pState, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_biquad_cascade_df1_q15_neOgvabhESQorERU2TIrPE(const arm_biquad_casd_df1_inst_q15 *S, const q15_t *pSrc, q15_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_biquad_cascade_df1_init_q15_neOgvabhESQorERU2TIrPE(arm_biquad_casd_df1_inst_q15 *S, uint8_T numStages, const q15_t *pCoeffs, q15_t *pState, int8_T postShift);
DLL_EXPORT_CC extern void arm_biquad_cascade_df1_fast_q15_neOgvabhESQorERU2TIrPE(const arm_biquad_casd_df1_inst_q15 *S, const q15_t *pSrc, q15_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_biquad_cascade_df1_q31_neOgvabhESQorERU2TIrPE(const arm_biquad_casd_df1_inst_q31 *S, const q31_t *pSrc, q31_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_biquad_cascade_df1_fast_q31_neOgvabhESQorERU2TIrPE(const arm_biquad_casd_df1_inst_q31 *S, const q31_t *pSrc, q31_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_biquad_cascade_df1_init_q31_neOgvabhESQorERU2TIrPE(arm_biquad_casd_df1_inst_q31 *S, uint8_T numStages, const q31_t *pCoeffs, q31_t *pState, int8_T postShift);
DLL_EXPORT_CC extern void arm_biquad_cascade_df1_f32_neOgvabhESQorERU2TIrPE(const arm_biquad_casd_df1_inst_f32 *S, const float32_t *pSrc, float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_biquad_cascade_df1_init_f32_neOgvabhESQorERU2TIrPE(arm_biquad_casd_df1_inst_f32 *S, uint8_T numStages, const float32_t *pCoeffs, float32_t *pState);
DLL_EXPORT_CC extern void arm_conv_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrcA, uint32_T srcALen, const float32_t *pSrcB, uint32_T srcBLen, float32_t *pDst);
DLL_EXPORT_CC extern void arm_conv_opt_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrcA, uint32_T srcALen, const q15_t *pSrcB, uint32_T srcBLen, q15_t *pDst, q15_t *pScratch1, q15_t *pScratch2);
DLL_EXPORT_CC extern void arm_conv_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrcA, uint32_T srcALen, const q15_t *pSrcB, uint32_T srcBLen, q15_t *pDst);
DLL_EXPORT_CC extern void arm_conv_fast_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrcA, uint32_T srcALen, const q15_t *pSrcB, uint32_T srcBLen, q15_t *pDst);
DLL_EXPORT_CC extern void arm_conv_fast_opt_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrcA, uint32_T srcALen, const q15_t *pSrcB, uint32_T srcBLen, q15_t *pDst, q15_t *pScratch1, q15_t *pScratch2);
DLL_EXPORT_CC extern void arm_conv_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrcA, uint32_T srcALen, const q31_t *pSrcB, uint32_T srcBLen, q31_t *pDst);
DLL_EXPORT_CC extern void arm_conv_fast_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrcA, uint32_T srcALen, const q31_t *pSrcB, uint32_T srcBLen, q31_t *pDst);
DLL_EXPORT_CC extern void arm_conv_opt_q7_neOgvabhESQorERU2TIrPE(const q7_t *pSrcA, uint32_T srcALen, const q7_t *pSrcB, uint32_T srcBLen, q7_t *pDst, q15_t *pScratch1, q15_t *pScratch2);
DLL_EXPORT_CC extern void arm_conv_q7_neOgvabhESQorERU2TIrPE(const q7_t *pSrcA, uint32_T srcALen, const q7_t *pSrcB, uint32_T srcBLen, q7_t *pDst);
DLL_EXPORT_CC extern arm_status arm_conv_partial_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrcA, uint32_T srcALen, const float32_t *pSrcB, uint32_T srcBLen, float32_t *pDst, uint32_T firstIndex, uint32_T numPoints);
DLL_EXPORT_CC extern arm_status arm_conv_partial_opt_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrcA, uint32_T srcALen, const q15_t *pSrcB, uint32_T srcBLen, q15_t *pDst, uint32_T firstIndex, uint32_T numPoints, q15_t *pScratch1, q15_t *pScratch2);
DLL_EXPORT_CC extern arm_status arm_conv_partial_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrcA, uint32_T srcALen, const q15_t *pSrcB, uint32_T srcBLen, q15_t *pDst, uint32_T firstIndex, uint32_T numPoints);
DLL_EXPORT_CC extern arm_status arm_conv_partial_fast_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrcA, uint32_T srcALen, const q15_t *pSrcB, uint32_T srcBLen, q15_t *pDst, uint32_T firstIndex, uint32_T numPoints);
DLL_EXPORT_CC extern arm_status arm_conv_partial_fast_opt_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrcA, uint32_T srcALen, const q15_t *pSrcB, uint32_T srcBLen, q15_t *pDst, uint32_T firstIndex, uint32_T numPoints, q15_t *pScratch1, q15_t *pScratch2);
DLL_EXPORT_CC extern arm_status arm_conv_partial_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrcA, uint32_T srcALen, const q31_t *pSrcB, uint32_T srcBLen, q31_t *pDst, uint32_T firstIndex, uint32_T numPoints);
DLL_EXPORT_CC extern arm_status arm_conv_partial_fast_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrcA, uint32_T srcALen, const q31_t *pSrcB, uint32_T srcBLen, q31_t *pDst, uint32_T firstIndex, uint32_T numPoints);
DLL_EXPORT_CC extern arm_status arm_conv_partial_opt_q7_neOgvabhESQorERU2TIrPE(const q7_t *pSrcA, uint32_T srcALen, const q7_t *pSrcB, uint32_T srcBLen, q7_t *pDst, uint32_T firstIndex, uint32_T numPoints, q15_t *pScratch1, q15_t *pScratch2);
DLL_EXPORT_CC extern arm_status arm_conv_partial_q7_neOgvabhESQorERU2TIrPE(const q7_t *pSrcA, uint32_T srcALen, const q7_t *pSrcB, uint32_T srcBLen, q7_t *pDst, uint32_T firstIndex, uint32_T numPoints);
DLL_EXPORT_CC extern void arm_fir_decimate_f32_neOgvabhESQorERU2TIrPE(const arm_fir_decimate_instance_f32 *S, const float32_t *pSrc, float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern arm_status arm_fir_decimate_init_f32_neOgvabhESQorERU2TIrPE(arm_fir_decimate_instance_f32 *S, uint16_T numTaps, uint8_T M, const float32_t *pCoeffs, float32_t *pState, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fir_decimate_q15_neOgvabhESQorERU2TIrPE(const arm_fir_decimate_instance_q15 *S, const q15_t *pSrc, q15_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fir_decimate_fast_q15_neOgvabhESQorERU2TIrPE(const arm_fir_decimate_instance_q15 *S, const q15_t *pSrc, q15_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern arm_status arm_fir_decimate_init_q15_neOgvabhESQorERU2TIrPE(arm_fir_decimate_instance_q15 *S, uint16_T numTaps, uint8_T M, const q15_t *pCoeffs, q15_t *pState, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fir_decimate_q31_neOgvabhESQorERU2TIrPE(const arm_fir_decimate_instance_q31 *S, const q31_t *pSrc, q31_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fir_decimate_fast_q31_neOgvabhESQorERU2TIrPE(const arm_fir_decimate_instance_q31 *S, const q31_t *pSrc, q31_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern arm_status arm_fir_decimate_init_q31_neOgvabhESQorERU2TIrPE(arm_fir_decimate_instance_q31 *S, uint16_T numTaps, uint8_T M, const q31_t *pCoeffs, q31_t *pState, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fir_interpolate_q15_neOgvabhESQorERU2TIrPE(const arm_fir_interpolate_instance_q15 *S, const q15_t *pSrc, q15_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern arm_status arm_fir_interpolate_init_q15_neOgvabhESQorERU2TIrPE(arm_fir_interpolate_instance_q15 *S, uint8_T L, uint16_T numTaps, const q15_t *pCoeffs, q15_t *pState, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fir_interpolate_q31_neOgvabhESQorERU2TIrPE(const arm_fir_interpolate_instance_q31 *S, const q31_t *pSrc, q31_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern arm_status arm_fir_interpolate_init_q31_neOgvabhESQorERU2TIrPE(arm_fir_interpolate_instance_q31 *S, uint8_T L, uint16_T numTaps, const q31_t *pCoeffs, q31_t *pState, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fir_interpolate_f32_neOgvabhESQorERU2TIrPE(const arm_fir_interpolate_instance_f32 *S, const float32_t *pSrc, float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern arm_status arm_fir_interpolate_init_f32_neOgvabhESQorERU2TIrPE(arm_fir_interpolate_instance_f32 *S, uint8_T L, uint16_T numTaps, const float32_t *pCoeffs, float32_t *pState, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_biquad_cas_df1_32x64_q31_neOgvabhESQorERU2TIrPE(const arm_biquad_cas_df1_32x64_ins_q31 *S, const q31_t *pSrc, q31_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_biquad_cas_df1_32x64_init_q31_neOgvabhESQorERU2TIrPE(arm_biquad_cas_df1_32x64_ins_q31 *S, uint8_T numStages, const q31_t *pCoeffs, q63_t *pState, uint8_T postShift);
DLL_EXPORT_CC extern void arm_biquad_cascade_df2T_f32_neOgvabhESQorERU2TIrPE(const arm_biquad_cascade_df2T_instance_f32 *S, const float32_t *pSrc, float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_biquad_cascade_stereo_df2T_f32_neOgvabhESQorERU2TIrPE(const arm_biquad_cascade_stereo_df2T_instance_f32 *S, const float32_t *pSrc, float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_biquad_cascade_df2T_f64_neOgvabhESQorERU2TIrPE(const arm_biquad_cascade_df2T_instance_f64 *S, const float64_t *pSrc, float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_biquad_cascade_df2T_init_f32_neOgvabhESQorERU2TIrPE(arm_biquad_cascade_df2T_instance_f32 *S, uint8_T numStages, const float32_t *pCoeffs, float32_t *pState);
DLL_EXPORT_CC extern void arm_biquad_cascade_stereo_df2T_init_f32_neOgvabhESQorERU2TIrPE(arm_biquad_cascade_stereo_df2T_instance_f32 *S, uint8_T numStages, const float32_t *pCoeffs, float32_t *pState);
DLL_EXPORT_CC extern void arm_biquad_cascade_df2T_init_f64_neOgvabhESQorERU2TIrPE(arm_biquad_cascade_df2T_instance_f64 *S, uint8_T numStages, const float64_t *pCoeffs, float64_t *pState);
DLL_EXPORT_CC extern void arm_fir_lattice_init_q15_neOgvabhESQorERU2TIrPE(arm_fir_lattice_instance_q15 *S, uint16_T numStages, const q15_t *pCoeffs, q15_t *pState);
DLL_EXPORT_CC extern void arm_fir_lattice_q15_neOgvabhESQorERU2TIrPE(const arm_fir_lattice_instance_q15 *S, const q15_t *pSrc, q15_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fir_lattice_init_q31_neOgvabhESQorERU2TIrPE(arm_fir_lattice_instance_q31 *S, uint16_T numStages, const q31_t *pCoeffs, q31_t *pState);
DLL_EXPORT_CC extern void arm_fir_lattice_q31_neOgvabhESQorERU2TIrPE(const arm_fir_lattice_instance_q31 *S, const q31_t *pSrc, q31_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fir_lattice_init_f32_neOgvabhESQorERU2TIrPE(arm_fir_lattice_instance_f32 *S, uint16_T numStages, const float32_t *pCoeffs, float32_t *pState);
DLL_EXPORT_CC extern void arm_fir_lattice_f32_neOgvabhESQorERU2TIrPE(const arm_fir_lattice_instance_f32 *S, const float32_t *pSrc, float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_iir_lattice_f32_neOgvabhESQorERU2TIrPE(const arm_iir_lattice_instance_f32 *S, const float32_t *pSrc, float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_iir_lattice_init_f32_neOgvabhESQorERU2TIrPE(arm_iir_lattice_instance_f32 *S, uint16_T numStages, float32_t *pkCoeffs, float32_t *pvCoeffs, float32_t *pState, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_iir_lattice_q31_neOgvabhESQorERU2TIrPE(const arm_iir_lattice_instance_q31 *S, const q31_t *pSrc, q31_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_iir_lattice_init_q31_neOgvabhESQorERU2TIrPE(arm_iir_lattice_instance_q31 *S, uint16_T numStages, q31_t *pkCoeffs, q31_t *pvCoeffs, q31_t *pState, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_iir_lattice_q15_neOgvabhESQorERU2TIrPE(const arm_iir_lattice_instance_q15 *S, const q15_t *pSrc, q15_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_iir_lattice_init_q15_neOgvabhESQorERU2TIrPE(arm_iir_lattice_instance_q15 *S, uint16_T numStages, q15_t *pkCoeffs, q15_t *pvCoeffs, q15_t *pState, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_lms_f32_neOgvabhESQorERU2TIrPE(const arm_lms_instance_f32 *S, const float32_t *pSrc, float32_t *pRef, float32_t *pOut, float32_t *pErr, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_lms_init_f32_neOgvabhESQorERU2TIrPE(arm_lms_instance_f32 *S, uint16_T numTaps, float32_t *pCoeffs, float32_t *pState, float32_t mu, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_lms_init_q15_neOgvabhESQorERU2TIrPE(arm_lms_instance_q15 *S, uint16_T numTaps, q15_t *pCoeffs, q15_t *pState, q15_t mu, uint32_T blockSize, uint32_T postShift);
DLL_EXPORT_CC extern void arm_lms_q15_neOgvabhESQorERU2TIrPE(const arm_lms_instance_q15 *S, const q15_t *pSrc, q15_t *pRef, q15_t *pOut, q15_t *pErr, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_lms_q31_neOgvabhESQorERU2TIrPE(const arm_lms_instance_q31 *S, const q31_t *pSrc, q31_t *pRef, q31_t *pOut, q31_t *pErr, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_lms_init_q31_neOgvabhESQorERU2TIrPE(arm_lms_instance_q31 *S, uint16_T numTaps, q31_t *pCoeffs, q31_t *pState, q31_t mu, uint32_T blockSize, uint32_T postShift);
DLL_EXPORT_CC extern void arm_lms_norm_f32_neOgvabhESQorERU2TIrPE(arm_lms_norm_instance_f32 *S, const float32_t *pSrc, float32_t *pRef, float32_t *pOut, float32_t *pErr, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_lms_norm_init_f32_neOgvabhESQorERU2TIrPE(arm_lms_norm_instance_f32 *S, uint16_T numTaps, float32_t *pCoeffs, float32_t *pState, float32_t mu, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_lms_norm_q31_neOgvabhESQorERU2TIrPE(arm_lms_norm_instance_q31 *S, const q31_t *pSrc, q31_t *pRef, q31_t *pOut, q31_t *pErr, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_lms_norm_init_q31_neOgvabhESQorERU2TIrPE(arm_lms_norm_instance_q31 *S, uint16_T numTaps, q31_t *pCoeffs, q31_t *pState, q31_t mu, uint32_T blockSize, uint8_T postShift);
DLL_EXPORT_CC extern void arm_lms_norm_q15_neOgvabhESQorERU2TIrPE(arm_lms_norm_instance_q15 *S, const q15_t *pSrc, q15_t *pRef, q15_t *pOut, q15_t *pErr, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_lms_norm_init_q15_neOgvabhESQorERU2TIrPE(arm_lms_norm_instance_q15 *S, uint16_T numTaps, q15_t *pCoeffs, q15_t *pState, q15_t mu, uint32_T blockSize, uint8_T postShift);
DLL_EXPORT_CC extern void arm_correlate_f32_neOgvabhESQorERU2TIrPE(const float32_t *pSrcA, uint32_T srcALen, const float32_t *pSrcB, uint32_T srcBLen, float32_t *pDst);
DLL_EXPORT_CC extern void arm_correlate_f64_neOgvabhESQorERU2TIrPE(const float64_t *pSrcA, uint32_T srcALen, const float64_t *pSrcB, uint32_T srcBLen, float64_t *pDst);
DLL_EXPORT_CC extern void arm_correlate_opt_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrcA, uint32_T srcALen, const q15_t *pSrcB, uint32_T srcBLen, q15_t *pDst, q15_t *pScratch);
DLL_EXPORT_CC extern void arm_correlate_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrcA, uint32_T srcALen, const q15_t *pSrcB, uint32_T srcBLen, q15_t *pDst);
DLL_EXPORT_CC extern void arm_correlate_fast_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrcA, uint32_T srcALen, const q15_t *pSrcB, uint32_T srcBLen, q15_t *pDst);
DLL_EXPORT_CC extern void arm_correlate_fast_opt_q15_neOgvabhESQorERU2TIrPE(const q15_t *pSrcA, uint32_T srcALen, const q15_t *pSrcB, uint32_T srcBLen, q15_t *pDst, q15_t *pScratch);
DLL_EXPORT_CC extern void arm_correlate_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrcA, uint32_T srcALen, const q31_t *pSrcB, uint32_T srcBLen, q31_t *pDst);
DLL_EXPORT_CC extern void arm_correlate_fast_q31_neOgvabhESQorERU2TIrPE(const q31_t *pSrcA, uint32_T srcALen, const q31_t *pSrcB, uint32_T srcBLen, q31_t *pDst);
DLL_EXPORT_CC extern void arm_correlate_opt_q7_neOgvabhESQorERU2TIrPE(const q7_t *pSrcA, uint32_T srcALen, const q7_t *pSrcB, uint32_T srcBLen, q7_t *pDst, q15_t *pScratch1, q15_t *pScratch2);
DLL_EXPORT_CC extern void arm_correlate_q7_neOgvabhESQorERU2TIrPE(const q7_t *pSrcA, uint32_T srcALen, const q7_t *pSrcB, uint32_T srcBLen, q7_t *pDst);
DLL_EXPORT_CC extern void arm_fir_sparse_f32_neOgvabhESQorERU2TIrPE(arm_fir_sparse_instance_f32 *S, const float32_t *pSrc, float32_t *pDst, float32_t *pScratchIn, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fir_sparse_init_f32_neOgvabhESQorERU2TIrPE(arm_fir_sparse_instance_f32 *S, uint16_T numTaps, const float32_t *pCoeffs, float32_t *pState, int32_T *pTapDelay, uint16_T maxDelay, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fir_sparse_q31_neOgvabhESQorERU2TIrPE(arm_fir_sparse_instance_q31 *S, const q31_t *pSrc, q31_t *pDst, q31_t *pScratchIn, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fir_sparse_init_q31_neOgvabhESQorERU2TIrPE(arm_fir_sparse_instance_q31 *S, uint16_T numTaps, const q31_t *pCoeffs, q31_t *pState, int32_T *pTapDelay, uint16_T maxDelay, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fir_sparse_q15_neOgvabhESQorERU2TIrPE(arm_fir_sparse_instance_q15 *S, const q15_t *pSrc, q15_t *pDst, q15_t *pScratchIn, q31_t *pScratchOut, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fir_sparse_init_q15_neOgvabhESQorERU2TIrPE(arm_fir_sparse_instance_q15 *S, uint16_T numTaps, const q15_t *pCoeffs, q15_t *pState, int32_T *pTapDelay, uint16_T maxDelay, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fir_sparse_q7_neOgvabhESQorERU2TIrPE(arm_fir_sparse_instance_q7 *S, const q7_t *pSrc, q7_t *pDst, q7_t *pScratchIn, q31_t *pScratchOut, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_fir_sparse_init_q7_neOgvabhESQorERU2TIrPE(arm_fir_sparse_instance_q7 *S, uint16_T numTaps, const q7_t *pCoeffs, q7_t *pState, int32_T *pTapDelay, uint16_T maxDelay, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_circularWrite_f32_neOgvabhESQorERU2TIrPE(int32_T *circBuffer, int32_T L, uint16_T *writeOffset, int32_T bufferInc, const int32_T *src, int32_T srcInc, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_circularRead_f32_neOgvabhESQorERU2TIrPE(int32_T *circBuffer, int32_T L, int32_T *readOffset, int32_T bufferInc, int32_T *dst, int32_T *dst_base, int32_T dst_length, int32_T dstInc, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_circularWrite_q15_neOgvabhESQorERU2TIrPE(q15_t *circBuffer, int32_T L, uint16_T *writeOffset, int32_T bufferInc, const q15_t *src, int32_T srcInc, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_circularRead_q15_neOgvabhESQorERU2TIrPE(q15_t *circBuffer, int32_T L, int32_T *readOffset, int32_T bufferInc, q15_t *dst, q15_t *dst_base, int32_T dst_length, int32_T dstInc, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_circularWrite_q7_neOgvabhESQorERU2TIrPE(q7_t *circBuffer, int32_T L, uint16_T *writeOffset, int32_T bufferInc, const q7_t *src, int32_T srcInc, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_circularRead_q7_neOgvabhESQorERU2TIrPE(q7_t *circBuffer, int32_T L, int32_T *readOffset, int32_T bufferInc, q7_t *dst, q7_t *dst_base, int32_T dst_length, int32_T dstInc, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_levinson_durbin_f32_neOgvabhESQorERU2TIrPE(const float32_t *phi, float32_t *a, float32_t *err, int32_T nbCoefs);
DLL_EXPORT_CC extern void arm_levinson_durbin_q31_neOgvabhESQorERU2TIrPE(const q31_t *phi, q31_t *a, q31_t *err, int32_T nbCoefs);
DLL_EXPORT_CC extern void arm_quaternion_norm_f32_neOgvabhESQorERU2TIrPE(const float32_t *pInputQuaternions, float32_t *pNorms, uint32_T nbQuaternions);
DLL_EXPORT_CC extern void arm_quaternion_inverse_f32_neOgvabhESQorERU2TIrPE(const float32_t *pInputQuaternions, float32_t *pInverseQuaternions, uint32_T nbQuaternions);
DLL_EXPORT_CC extern void arm_quaternion_conjugate_f32_neOgvabhESQorERU2TIrPE(const float32_t *inputQuaternions, float32_t *pConjugateQuaternions, uint32_T nbQuaternions);
DLL_EXPORT_CC extern void arm_quaternion_normalize_f32_neOgvabhESQorERU2TIrPE(const float32_t *inputQuaternions, float32_t *pNormalizedQuaternions, uint32_T nbQuaternions);
DLL_EXPORT_CC extern void arm_quaternion_product_single_f32_neOgvabhESQorERU2TIrPE(const float32_t *qa, const float32_t *qb, float32_t *r);
DLL_EXPORT_CC extern void arm_quaternion_product_f32_neOgvabhESQorERU2TIrPE(const float32_t *qa, const float32_t *qb, float32_t *r, uint32_T nbQuaternions);
DLL_EXPORT_CC extern void arm_quaternion2rotation_f32_neOgvabhESQorERU2TIrPE(const float32_t *pInputQuaternions, float32_t *pOutputRotations, uint32_T nbQuaternions);
DLL_EXPORT_CC extern void arm_rotation2quaternion_f32_neOgvabhESQorERU2TIrPE(const float32_t *pInputRotations, float32_t *pOutputQuaternions, uint32_T nbQuaternions);
DLL_EXPORT_CC extern void arm_welch_f64_neOgvabhESQorERU2TIrPE(float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_welch_f32_neOgvabhESQorERU2TIrPE(float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_bartlett_f64_neOgvabhESQorERU2TIrPE(float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_bartlett_f32_neOgvabhESQorERU2TIrPE(float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_hamming_f64_neOgvabhESQorERU2TIrPE(float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_hamming_f32_neOgvabhESQorERU2TIrPE(float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_hanning_f64_neOgvabhESQorERU2TIrPE(float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_hanning_f32_neOgvabhESQorERU2TIrPE(float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_nuttall3_f64_neOgvabhESQorERU2TIrPE(float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_nuttall3_f32_neOgvabhESQorERU2TIrPE(float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_nuttall4_f64_neOgvabhESQorERU2TIrPE(float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_nuttall4_f32_neOgvabhESQorERU2TIrPE(float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_nuttall3a_f64_neOgvabhESQorERU2TIrPE(float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_nuttall3a_f32_neOgvabhESQorERU2TIrPE(float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_nuttall3b_f64_neOgvabhESQorERU2TIrPE(float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_nuttall3b_f32_neOgvabhESQorERU2TIrPE(float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_nuttall4a_f64_neOgvabhESQorERU2TIrPE(float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_nuttall4a_f32_neOgvabhESQorERU2TIrPE(float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_blackman_harris_92db_f64_neOgvabhESQorERU2TIrPE(float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_blackman_harris_92db_f32_neOgvabhESQorERU2TIrPE(float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_nuttall4b_f64_neOgvabhESQorERU2TIrPE(float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_nuttall4b_f32_neOgvabhESQorERU2TIrPE(float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_nuttall4c_f64_neOgvabhESQorERU2TIrPE(float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_nuttall4c_f32_neOgvabhESQorERU2TIrPE(float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_hft90d_f64_neOgvabhESQorERU2TIrPE(float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_hft90d_f32_neOgvabhESQorERU2TIrPE(float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_hft95_f64_neOgvabhESQorERU2TIrPE(float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_hft95_f32_neOgvabhESQorERU2TIrPE(float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_hft116d_f64_neOgvabhESQorERU2TIrPE(float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_hft116d_f32_neOgvabhESQorERU2TIrPE(float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_hft144d_f64_neOgvabhESQorERU2TIrPE(float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_hft144d_f32_neOgvabhESQorERU2TIrPE(float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_hft169d_f64_neOgvabhESQorERU2TIrPE(float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_hft169d_f32_neOgvabhESQorERU2TIrPE(float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_hft196d_f64_neOgvabhESQorERU2TIrPE(float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_hft196d_f32_neOgvabhESQorERU2TIrPE(float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_hft223d_f64_neOgvabhESQorERU2TIrPE(float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_hft223d_f32_neOgvabhESQorERU2TIrPE(float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_hft248d_f64_neOgvabhESQorERU2TIrPE(float64_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void arm_hft248d_f32_neOgvabhESQorERU2TIrPE(float32_t *pDst, uint32_T blockSize);
DLL_EXPORT_CC extern void vEstimationSystemComputeEstimate_neOgvabhESQorERU2TIrPE(float32_t u1, float32_t u2, float32_t z1, float32_t z2);
DLL_EXPORT_CC extern void __PROGRAM_START_neOgvabhESQorERU2TIrPE(void);

/* Function Definitions */
DLL_EXPORT_CC const uint8_T *get_checksum_source_info(int32_T *size);
#ifdef __cplusplus
}
#endif

